1024pix/pix-bot

lib/controllers/slack.js
lib/routes/slack.js
lib/services/releases.js
lib/services/slack/commands.js
package-lock.json
package.json
scripts/common.sh
scripts/deploy.sh
scripts/get-pull-requests-to-release-in-prod.js
scripts/publish.sh

A l'image de la commande Slack `/deploy-release [release_tag]` qui permet d'installer les apps Pix sur l'environnement de production, nous aimerions rendre la publication et le déploiement sur l'environnement de recette d'une nouvelle _release_ accessible et exécutable au travers une nouvelle commande `/publish-release [version_type]`.
Cette PR se contente de la version commande Slack et ne couvre pas la feature shortcut + model-based workflow proposé pour la procédure de déploiement.

Publier une release et la déployer en recette depuis la commande Slack `/publish-release`.

---

lib/controllers/releases.js
lib/controllers/slack.js
lib/routes/releases.js
lib/routes/slack.js
lib/services/releases.js
lib/services/slack/commands.js
scripts/release-pix-site.sh

Les mises en production de Pix-Site se font encore par un développeur. 
Permettre à une application slack de lancer une mise en production. 
Ajout d'un nouvel endpoint : `/slack/commands/create-and-deploy-pix-site-release`

Permettre la mise en production de Pix.fr depuis Slack. 

---

scripts/deploy.sh

Il n'est pas possible de revenir sur une version précédente de la production en utilisant pix-bot. 
Ajouter l'option `-f`  à la commande `git push` pour permettre de pousser la version que l'on souhaite en production.

[FEATURE] Permettre de déployer une ancienne version.

---

package-lock.json
package.json

Scalingo impose une restriction sur le nombre d'opérations en cours d'exécution (ex: scaling, création, suppression d'apps), cf. #4.  
La dernière version de la dépendance [scalingo-review-app-manager]( https://github.com/1024pix/scalingo-review-app-manager/pull/1) dont dépend Pix Bot, tient compte de cette limite. 
Cette PR effectue la montée de version.

[BUGFIX] Pouvoir gérer un nombre important de review apps. 

---

README.md
lib/config.js
lib/controllers/slack.js
lib/routes/slack.js
lib/services/github.js
sample.env
scripts/common.sh
test/unit/services/github_test.js

Ajout d'une route /slack/pull-requests qui retourne la liste des PR ouvertes d'après un label

[FEATURE] Ajout d'une route pour récupérer les PR ouverte

---

package-lock.json
package.json

Cette [nouvelle version](https://github.com/1024pix/scalingo-review-app-manager/releases/tag/v1.0.0) de `scalingo-review-app-manager` corrige des failles et permet de spécifier la time zone des _cron jobs_.

[INFRA] Montée de version de scalingo-review-app-manager

---

lib/controllers/slack.js
lib/routes/slack.js
lib/services/github.js

Il y avait 2 problèmes : 
1. collision de 2 variables de type `const` (l'une issue d'un import en en-tête du module, l'autre comme variable locale) au sein d'une méthode d'un méthode qui fait qu'on avait une erreur de type `variable inaccessible avant l'initialisation`
2. Pix Bot implémentant la procédure de vérification du token de l'appelant comme préconisé par la doc de Slack, celle-ci a été mutualisée dans un pre-handler Hapi.js, dont le but est de parser correctement l'éventuel payload de la requête et d'alimenter une variable de pre-handler `request.pre.handler`
> **Note personnelle** : le fait qu'il n'y ait qausiment pas de tests auto et qu'il n'y a pas de CI, ce type de double-bug malgré la revue de code est dommage, mais pas surprenant.
J'ai reproduit, débuggué, testé et fait …

[BUGFIX] Mise en marche de la commande Slack `/pr-pix [team-name]`

---

bin/www

Suite à la montée de version (majeure) de scalingo-review-app-manager, il est désormais possible de définir la zone de temps des jobs cron. Par défaut, il semblerait que les serveurs Outscale soient branchés sur l'heure de Paris + 2h. Afin de déclencher les actions sur les RA au bon moment, il convient de fixer la timezone.

[BUGFIX] L'éco-mode des Review Apps intervient 2h plus tard que l'horaire défini

---

scripts/deploy.sh

Un espace qui s'est glissé sur une variable 🤦‍♂️

[BUGFIX] La procédure de MEP échoue tout à la fin au moment de finaliser la release Sentry associée à la MEP

---

lib/config.js
lib/controllers/slack.js
lib/routes/slack.js
lib/services/google-sheet.js
sample.env
test/unit/services/google-sheet_test.js

💡 Objectif 💡
- Pouvoir avoir un tip sur l'a11y via une commande slack
🚗 Fonctionnement 🚗 
- Ajout d'une route API  /slack/commands/accessibility-tip
- Connexion simple à un Google Sheet avec les tips : https://docs.google.com/spreadsheets/d/1rZoiXlbBeVMEDuirn6V-SLtgD8rYqlc5Sfr0m7AKJeU/edit#gid=0
- Choix aléatoire d'un tip
- Création du message au format slack

[FEATURE] Ajout de l'API pour la commande slack /a11y-tip

---

README.md
lib/config.js
lib/services/github.js
lib/services/releases.js
lib/services/slack/view-submissions.js
package-lock.json
package.json
sample.env
scripts/common.sh
scripts/deploy.sh
scripts/publish.sh
scripts/release-pix-repo.sh
test/unit/services/github_test.js
test/unit/services/google-sheet_test.js
test/unit/test-helper.js

Le script de publication de la release contient à la fois la création **et** le déploiement.
Pour uniformiser les tâches, le script de création et publication de la release ne déploie plus la release en recette. (fichier `publish.sh`).
La commande Slack permettant de faire la mise en recette appelle désormais le script de création de release puis le script de déploiement de la release créée sur l'environnement `Recette`.
Dans le cas de la publication d'une release, les 2 scripts étant décorrelés, il faut trouver un moyen de récupérer le LTR (Last Release Tag) généré après création de la release, pour pouvoir le passer à la procédure de déploiement sur recette. Pour se faire, nous utilisons l'API GitHub et son client Node.js officiel ([Octokit.js](https://github.com/octokit/core.js)). Pour …

[Cleanup] Séparer les tâches de publication et de déploiement d'une release.

---

bin/www
lib/config.js
lib/services/releases.js
lib/services/scalingo-client.js
package-lock.json
package.json
sample.env
scripts/publish.sh
test/unit/services/releases_test.js
test/unit/services/scalingo-client_test.js

Pour rappel, les applications Pix API, Admin, App, Certif & Orga sont hébergées par Scalingo (PaaS) / 3DS Outscale (IaaS). 
Le déploiement d’une nouvelle version de la plateforme et de chaque application se fait via l’application Pix Bot (déclenchée depuis une commande Slack), laquelle exécute un script Shell, qui se termine par un push (du commit du tag livré) sur la branche prod du repository 1024pix/pix.
Ce mécanisme est fonctionnel depuis des mois.
Cependant, le fait de lier aussi fortement GitHub (hébergeur de code source) et Scalingo (hébergeur de l’applicatif) nous paraît risqué à terme, car trop rigide ou trop fragile, à tout le moins pour les applications de production.
Nous pensons qu’il serait préférable et plus pérenne de dissocier GitHub de Scalingo en production.
Par …

[TECH] Utiliser le déploiement manuel par archive proposé par Scalingo plutôt que le trigger GitHub

---

lib/services/slack/commands.js
scripts/common.sh
test/unit/services/releases_test.js
test/unit/services/slack/commands_test.js

Le déploiement de pix-site échoue si on ne spécifie pas le type de release dans la commande slack.
Mettre le type de release à `minor` si celui-ci n'est pas défini par l'utilisateur.
On en a profité pour limiter le clone du repo git au dernier commit car on ne se sert pas de l'historique.
Faire un déploiement de pix-site depuis la commande `/deploy-pix-site` sans argument.

[BUGFIX] Correction de l'échec du déploiement de pix-site quand le type de release n'est pas spécifié.

---

README.md

Pas d'info sur le repo pix-bot-test-release et la commande associé dans pix-bot
Ajout d'information dans le README
Cette fonctionalité pourra etre supprimé si besoin

Ajouter la doc pour pix bot test release via slack

---

lib/controllers/slack.js
lib/routes/slack.js
lib/services/releases.js
lib/services/slack/commands.js
scripts/common.sh
scripts/deploy-pix-ui.sh
scripts/get-pull-requests-to-release-in-prod.js
scripts/publish.sh
scripts/release-pix-repo.sh
test/get-pull-requests-to-release-in-prod_test.js
test/unit/services/releases_test.js
test/unit/services/slack/commands_test.js

Les déploiements de nouvelles versions d'applis se font via Slack.
Il y manque le déploiement de pix-ui.
- Créer le script de déploiement de pix-ui `deploy-pix-ui.sh`
- Créer la commande Slack qui appelera ce script
- Réutilisation du script de release de pix-site `release-pix-repo.sh` + ajout de l'écriture de changelog dans ce script

[TECH] Ajout d'une action Slack pour déployer pix-ui

---

lib/controllers/slack.js
lib/routes/slack.js
lib/server.js
lib/services/github.js
lib/services/releases.js
lib/services/scalingo-client.js
lib/services/slack/commands.js
package-lock.json
package.json
scripts/get-pull-requests-to-release-in-prod.js
scripts/release-pix-repo.sh
test/get-pull-requests-to-release-in-prod_test.js
test/unit/services/github_test.js
test/unit/services/releases_test.js
test/unit/services/scalingo-client_test.js
test/unit/services/slack/commands_test.js

La nouvelle API LCMS (Learning Content Management System) ne peut être déployée automatiquement par qui que ce soit.
Seul un·e développeu·r·se peut le faire via le client Scalingo en local.
Adapter le fonctionnement du déploiement des sites `pix.fr` et `pro.pix.fr` pour offrir une commande slack `/deploy-pix-lcms` qui crée la release et la déploie en production.
Il n'existe pas d'environnement de recette pour le moment pour cette application.
En local, appeler la route `POST /slack/commands/create-and-deploy-pix-lcms-release`.
Le body de la requête doit contenir les champs suivants : 
- "text": "patch | minor | major", 
- "response_url": "<url pour la réponse à slack, pour le test on peut mettre> https://httpbin.org/status/200"

[FEATURE] Ajout du déploiement de l'API LCMS.

---

lib/services/github.js
test/unit/services/github_test.js

Suite au merge de la PR #30 la procédure de release pour les applications Pix (Pix API, Pix App, etc.) ne fonctionne plus.
Le problème venait d'un mauvais mapping de la réponse d'une requête à l'API GitHub via Octokit.

[BUGFIX] Correction du script de publication d'une nouvelle release.

---

scripts/get-pull-requests-to-release-in-prod.js
scripts/release-pix-repo.sh

Lors de la création d'une release, on essaie de mettre à jour le `CHANGELOG.md`.
S'il n'existe pas, on l'initialiser avec une chaine vide.
Cela ne fonctionne pas car le script s'attend à avoir un fichier contenant a minima l'entete (2 lignes).
En échouant cette mise à jour, cela met également en échec le processus de release.
Initialisation du fichier `CHANGELOG.md` avec l'entete si le fichier n'existe pas.
Il faut enlever l'option `--update` du `git add` pour ce fichier sinon il n'ajoute pas de nouveau fichier.
Lancer le script `get-pull-requests-to-release-in-prod` sur un repo ne contenant pas de CHANGELOG.
Vérifier que le CHANGELOG a bien été créé.

[BUGFIX] Corrige la création du fichier `CHANGELOG.md` s'il n'existe pas.

---

lib/services/slack/commands.js

L'application `pix-lcms-api-production` a été renommée en `pix-lcms-production` (sur Scalingo) car elle héberge à la fois l'api et le front (Pix Editor).
Comme le nom n'a pas été modifié dans pix bot, il n'est plus possible de déployer PIX LCMS.
Modifier le nom de l'application utilisée par le bot pour déployer sur Scalingo.
RAS
Merger, déployer PIX LCMS depuis Slack, prier.

[BUGFIX] Correction du nom de l'application PIX LCMS.

---

lib/controllers/slack.js
lib/services/github.js
lib/services/slack/surfaces/messages/post-message.js
lib/services/slack/view-submissions.js
test/unit/services/github_test.js

Aucune vérification n'est faite sur l'environnement applicatif précédent avant une MER ou MEP.
Cette PR répond en partie à l'issue https://github.com/1024pix/pix-bot/issues/15
Avant une MER, vérifier que la CI en intégration soit OK, sinon envoyer un message slack sur le channel tech-release.
Avant une MEP, vérifier que la CI en recette soit OK, sinon envoyer un message slack sur le channel tech-release.
API d'envoi de message d'erreur testé fonctionnellement.
Le channel #tmp-channel-test-pix-bot existe, si vous souhaitez checkout la branche. Dans ce cas, il faut penser à changer le nom du channel Slack dans le fichier `post-message.js`.

[TECH] Ajout de vérification CI avant MER/MEP

---

lib/services/slack/surfaces/messages/post-message.js

Il y a une typo dans le nom du channel Slack.
Fix typo dans le nom du channel Slack

[BUGFIX] Fix typo dans le nom du channel Slack

---

lib/services/github.js
test/unit/services/github_test.js

Lorsqu'on récupère les PR ouvertes d'une équipe, on a pas d'information sur son statut
Pour ne pas faire trop long, on récupère l'emoji lié au label:
🚧  => en cours de développement
👀   => review needed
🚀 => ready to merge
On pourrait ajouter un paramètre pour filtrer par type/label de PR
sur slack, lancer `/pr-pix team-certif` et voir le les icônes s'afficher
> 
> 👀 [TECH] Enlever les actions synchrones qui bloquent nodejs
> 🚧  [TECH] Renommer les routes api/jury en api/admin
> 🚀 [TECH] Ajout d'un script permettant de visualiser une certif VS le profil de positionnement

[FEATURE] Display Pull-request labels on slack message

---

lib/controllers/slack.js
lib/routes/slack.js
lib/services/releases.js
lib/services/slack/commands.js
test/unit/services/releases_test.js
test/unit/services/slack/commands_test.js

**⚠️ Cette PR devra être mergée quand la migration pix-pro dans pix-site sera complètement terminée ⚠️** 
Suite à la migration de pix-pro dans pix-site le processus de déploiement en production n'est plus le même. Avant cette migration pix-site et pix-pro étaient dans des repositories différents avec chacun sa commande slack dédiée pour être déployé.
Voici une schématisation du processus de déploiement actuel:
Comme pix-site et pix-pro sont désormais sur le même repository, il n'y aura qu'une seule commande qui réalisera le déploiement des 2 sites. Et les 2 sites partageront le même tag déployé sur 2 instances (une pour pix-site et une pour pix-pro)
- Il faudra supprimer la commande `/deploy-pix-pro` de Slack
- Cette PR devra être mergée quand la migration pix-pro dans pix-site sera …

[FEATURE] Deployer pix-site et pix-pro désormais dans le même repo (PIX-1266)

---

scripts/publish.sh

La PR [https://github.com/1024pix/pix/pull/2038]() ajoute l'envoie des exceptions de `pix-app` vers Sentry.
Actuellement, la publication d'une release de pix ne créée pas de release Sentry pour `pix-app` et il est donc impossible d'utiliser Sentry pour détecter les commits introduisant de nouvelles exceptions.
Ajout de la création de la release Sentry de `pix-app` lors de la création de la release de pix.
RAS
Après la publication d'une release, vérifier que les exceptions dans Sentry sur `pix-app` sont bien classées dans une release et que les commits associés sont disponibles.

[TECH] Création de la release de `pix-app` sur Sentry.

---

lib/config.js
lib/controllers/deploy-sites.js
lib/routes/deploy-sites.js
sample.env

Les sites pix.fr et pro.pix.fr migrent vers une architecture statique.
Ils ne feront donc plus d'appels au CMS pour récupérer les pages, cela rend donc obligatoire de reconstruire les sites pour publier de nouvelles pages.
Prismic offre la possibilité de configurer un webhook lors de la modification / création d'une page.
En pratique, cela revient à configurer une url qui est appelée lors de ces événements. Prismic permet également d'ajouter un secret dans le corps de la requête pour authentifier l'appel.
On crée donc une route `POST /build-sites` qui récupère le nom de la dernière version en production et demande à Scalingo de la redéployer.
RAS
A définir

[FEATURE] Ajout du déploiement automatique des sites statiques lors de la modification/création d'une page sur le CMS (Prismic).

---

.gitignore
lib/services/github.js
test/unit/services/github_test.js

Lorsque des branches filles sont mergées dans une branche mère, mais que celle-ci n'est pas la branche de base, leur merge apparaît quand même dans le changelog.
Exemple :
Une branche US1-part1 et une branche US1-part2 sont revue techniquement et mergées dans la branche mère US1. La branche mère n'est pas encore mergée dans la branch dev (branche de référence), et toujours soumise à revue fonctionnelle. Le merge de ces 2 branches filles apparaissent dans le changelog de la version, alors même que la fonctionnalité n'est pas incluse.
Spécifier la base branche pour récupérer les PR mergées.
NA
?

Spécifier la base branch pour générer le CHANGELOG (PIX-1417).

---

lib/services/slack/commands.js

Quand on lance un déploiement de Pix-UI sur slack via la commande `/publish-pix-ui [patch|minor|major]` Pix bot nous donne 2 retours mais via des messages privés (voir image ci-dessous). Et donc non visible de tous.
Cela peut devenir embêtant si on ne sait pas qui déploie une nouvelle version ni quand.
Rajouter un message d'information sur slack visible pour tous, après un déploiement de pix-ui.

[TECH] Ajout d'un message d'information sur slack pour les déploiement de Pix-UI 

---

lib/services/github.js
package-lock.json
package.json

La PR #39 a ajouté la spécification de branche de base utilisée pour le CHANGELOG.
Malheureusement, la récupération de la branche par défaut est fait par un appel sans `credentials`, ce qui fonctionne pour la plupart des répos car ils sont publiques.
`pix-editor` en revanche est un repo privé et donc cet appel échoue et bloque la mise en production de l'application.
Utiliser `Octokit`, le client node officiel de GitHub pour spécifier la clé d'API et ainsi pouvoir accéder aux données des repos privés.
Il faut privilégier l'utilisation d'Octokit plutôt que de faire des appels directement via `axios` ou autre paquet du même genre.
Lancer le script de computation du CHANGELOG sur pix-editor et vérifier que celui-ci se déroule sans erreur.

[BUGFIX] Corriger la récupération de la branche par défault des repos privés.

---

lib/controllers/slack.js
lib/routes/slack.js
lib/services/slack/commands.js
test/unit/lib/services/slack/commands_test.js

Les applications `pix-datawarehouse-production` et `pix-datawarehouse-ex-production` ne sont plus déployées automatiquement depuis GitHub.
Aucune release n'est faite actuellement, aussi il est compliqué de déployer des mises à jour.
On tire profit de `pix-bot` en ajoutant une commande `/deploy-pix-datawarehouse` qui permet de générer le CHANGELOG, créer la release (tag Git) et de publier les applications sur Scalingo.
RAS
A définir

[Feature] Ajout d'une commande /deploy-pix-datawarehouse.

---

lib/services/slack/commands.js
test/unit/lib/services/slack/commands_test.js

Si pour une raison quelconque la release fail, nous n'avons aucun retour de la part de pix-bot coté slack.
Envoyer un message à l'utilisateur pour l'informer que la release a échoué.
_Néant_
:open_mouth: Impossible, aucune erreur ne s'est jamais produite.

[TECH] Informe l'utilisateur de la commande que celle ci à échoué

---

lib/services/cdn.js
test/integration/lib/services/cdn_test.js

La requête faite pour invalider le cache tombe en erreur car il manque le pattern des fichiers à invalider.
Ajouter le pattern 

[BUGFIX] Ajouter le pattern des fichiers à invalider dans le cache.

---

.circleci/config.yml

Aujourd'hui il n'y a aucune vérification automatique des tests et du lint du code de PixBot.
Ajouter circle ci dans le workflow de pix bot.
RAS
Constater que circle CI tourne pour PixBot : https://app.circleci.com/pipelines/github/1024pix/pix-bot/1/workflows/6e6baa5e-65af-4889-992c-a1bf79a77ee9

Ajout d'une configuration circle ci

---

lib/services/slack/commands.js

Aujourd'hui s'il y a un soucis avec une release de Pix-UI un message **_privé_** est remonté à la personne ayant lancé le script dans Slack.
Seule la personne ayant lancé le script pourra voir ce message là. Or, pour rendre le débug et la maintenabilité plus simple ce message ci devrait être publique.
Faire afficher publiquement le message d'erreur s'il y en a un.
RAS
RAS

Remonter publiquement les erreurs de release de Pix-UI

---

package-lock.json
package.json

La dépendance scalingo-review-app-manager, dans sa version 1.0.0, présentait une vulnérabilité dans la dépendances axios portée par la dépendance scalingo. De fait, nous avons publié une nouvelle version du package scalingo-review-app-manager, la 1.0.1, qui met à jour les paquets nécessaires afin de résoudre la vulnérabilité.
Aussi, PixBot utilise directement la dépendance scalingo, laquelle nous avons également monté la version.
Mettre à jour scalingo-review-app-manager de 1.0.0 vers 1.0.1
Mettre à jour scalingo de 0.1.1 vers 0.3.1

[TECH] Mise à jour des dépendances scalingo-review-app-manager et scalingo

---

package.json

Actuellement, le script de déploiement de version n'envoie que le tag mais pas le commit associé.
Envoyer le commit associé au tag. 

[TECH] Pusher le commit de version en même temps que le tag

---

common/controllers/slack.js
common/routes/slack.js
common/services/scalingo-client.js
run/services/slack/commands.js
test/unit/common/services/scalingo-client_test.js
test/unit/run/services/slack/commands_test.js

Actuellement, le déploiement de `pix-bot-build` et `pix-bot-run` se fait manuellement.
Pouvoir déployer `pix-bot-build` et `pix-bot-run` via pix-bot et une commande Slack `/deploy-pix-bot [release type]`.
Tâches à réaliser:
```
POST /slack/commands/create-and-deploy-pix-bot-release
```

[FEATURE] Deployer pix bot avec pix bot

---

scripts/common.sh
scripts/publish.sh
scripts/release-pix-repo.sh

Le script de release est lié à la branche dev au moment du push de tag.
Faire en sorte de ne plus être lié à la branche dev dans le script..

Suppression du nom de la branche dans le script de release

---

common/services/scalingo-client.js
test/unit/common/services/scalingo-client_test.js

Il peut être lourd de devoir saisir le nom entier de l'application lors de l'appel à la commande Slack `/app-status`
Permettre à la commande Slack de comprendre les noms raccourcis des applications.  
Dans ce cas, ce sera automatiquement l'application de prod qui sera visée.
Ex:
- avant il fallait saisir `/app-status pix-app-production`
- maintenant il est aussi possible de saisir `/app-status app`: cette commande retournera le status de l'application pix-app-production
On a aussi porfité de cette PR pour corriger un problème sur la commande.  
Sur la PR #65 qui permet de remonter sur Slack le status d'un application Scalingo, on remarque que le status de l'api est toujours DOWN parce que l'on ping `https://app.{environement}.pix.fr` et non pas `https://app.{environement}.pix.fr/api`. …

Pouvoir saisir des noms d'app raccourci sur la commande app-status

---

common/services/scalingo-client.js
run/services/slack/app-status-from-scalingo.js
test/unit/run/services/slack/app-status-from-scalingo_test.js

Losque /app-status est appelé avec un nom court (ex: `/app-status app`), Slack ne parvient pas à retourner le status d'une application.
Pour connaitre la région Scalingo à requêter, on se basait sur le suffixe du nom de l'application.
Par exemple, si le nom est `pix-app-production`, alors la région est celle de la prod.
Or, en renseignant seulement `app` comme nom d'application, on requêtait la région de recette.
La région par défaut à requêter à été changé pour la prod.

[BUGFIX] Appel à /app-status avec un nom court

---

common/services/scalingo-client.js
run/services/slack/app-status-from-scalingo.js
test/unit/common/services/scalingo-client_test.js
test/unit/run/services/slack/app-status-from-scalingo_test.js

Aujourd'hui, la commande `/app-status` prend en paramètre le nom d'une app et ne retourne que le statut de celle-ci. Nous voudrions pouvoir obtenir le statut de toutes les apps avec une seule commande.
Ajouter la possibilité de passer l'environnement comme paramètre à la commande `/app-status` pour obtenir le statut des apps de cet environnement.
Nous avons choisi de retourner le statut des apps Scalingo qui nous paraissaient le plus importantes : api, app, orga, certif, admin. Il est toujours possible d'obtenir manuellement le statut des autres (ex: `/app-status pix-site-production`).

[FEATURE] Obtenir le statut de toutes les apps plutôt qu'une seule

---

common/controllers/slack.js
common/routes/slack.js
run/services/slack/commands.js

Le endpoint `/slack/commands/create-and-deploy-pix-bot-test-release` est un endpoint de test qui n'est plus utilisé.
Supprimer cet endpoint.

[TECH] Supprimer un endpoint inutilisé

---

README.md

Il est difficile de se plonger dans Pix Bot, entre le split de Pix Bot et le déploiment de Pix Bot désormais fait depuis Slack.
Documenter:
- le split de Pix Bot
- comment tester fonctionnellement un nouvel endpoint appelé depuis Slack
- le déploiement Pix Bot depuis Slack

Mise à jour de la documentation

---

config.js
run/services/slack/app-status-from-scalingo.js
sample.env
test/unit/run/services/slack/app-status-from-scalingo_test.js

Il n'est pas possible de lister le status des applications en intégration
Ajouter la possibilité de lister le status des applications en intégration via la commande `/app-status integration`
Nouvelles variables d'environnement:
- SCALINGO_TOKEN_INTEGRATION
- SCALINGO_API_URL_INTEGRATION

Affichage des statuts des app en intégration

---

common/controllers/slack.js
common/routes/slack.js
common/services/releases.js
common/services/slack/surfaces/messages/block-message.js
run/controllers/deploy-sites.js
run/services/slack/commands.js
test/unit/common/services/releases_test.js
test/unit/run/services/slack/commands_test.js

Actuellement, pour redéployer une application il faut passer par Scalingo.
Pour l'intégration et la recette, cela peut se faire via l'interface de Scalingo.
Mais pour la production, il faut se connecter au client en ligne de commande.
Il nous faudrait un moyen simple pour redéployer une application.
Grâce à la commande `/redeploy-app [_app-name_]`:
- le dernier tag Github du repo pix sera récupéré
- le redéploiment de la dernière version sera démarré

Redéployer une application via Slack

---

common/services/github.js
test/unit/build/services/github_test.js

On manque d'information sur les reviews affichés dans slack.
Afficher le statut des review (nombre d'`approved`, nombre de `comments` et de `request change`)
On trie en plaçant en dernier les PR en cours de développement
En local uniquement.
Lancer Pix-bot avec npm start.
Lancer ngrock avec ngrok http 3000.
Configurer la commande /pr-pix de l'environnement Slack Pix-Bot-Test avec l'adresse donnée par ngrok suivi de /slack/commands/pr-pix
Taper la commande `/pr-pix cross-team`
Verifier le message afficher

[Feature] Ajout d'info dans les message slack de PRs

---

common/controllers/slack.js
common/routes/slack.js
common/services/releases.js
scripts/common.sh
scripts/dummy-script.sh
scripts/publish.sh
test/integration/common/services/releases_test.js
test/unit/common/services/releases_test.js

La création d‘un hotfix se fait actuellement entièrement manuellement.
Par définition, le hotfix est nécessaire dans des conditions de stress inhabituelles.
Dépendre d'une opération manuelle est une source de stress additionnelle.
Pour la santé mentale de l‘équipe technique, on ajoute une commande slack `/deploy-hotfix [branch-name]`.
Cette commande appelle un endpoint de Pix-bot qui se charge de créée une nouvelle release de type `patch` à partir de la branche donnée.
Après publication, la release est déployée en recette.
Après la recette du hotfix, on peut le déployer en production en utilisant Slack comme à l'accoutumée.
Il suffira de préciser le nom du hotfix comme nom de version à mettre en production.
Il faudra par la suite créer une Pull-Request depuis la branche de hotfix vers …

[FEATURE] Ajoute la commande de création, publication et déploiement en recette d'un patch (hotfix).

---

common/controllers/slack.js
common/services/github.js
scripts/common.sh
scripts/get-pull-requests-to-release-in-prod.js
test/unit/build/services/github_test.js

La commande de hotfix a échouée, car elle ne récupérait pas la bonne version à déployer et ne générait pas le changelog à partir de la branche de hotfix.
- Récupérer correctement la version du hotfix à déployer
- Donner le nom de la branche de hotfix au script de génération du changelog
N/A
Faire un hotfix 🤯

[TECH] Correction de la commande de hotfix Slack

---

scripts/release-pix-repo.sh

Au moment du hotfix, une erreur apparait:
'/app/scripts/common.sh: line 19: BRANCH_NAME: unbound variable\n'
Définir la variable BRANCH_NAME dans release-pix-repo.sh

[TECH] Corriger l'utilisation de la variable BRANCH_NAME dans common.sh

---

run/services/slack/commands.js
test/unit/run/services/slack/commands_test.js

La commande Slack `/deploy-last-version pix-site-production` n'aurait pas dû être exécutée car la commande déploie seulement les applications issues du repository Pix.
Ajouter un retour d'erreur si le nom de l'application passée en paramètre ne correspond pas à une application au format`pix-['app', 'certif', 'admin', 'orga', 'api']-['integration', 'recette', 'production']`.
Il existe une commande Slack pour déployer pix-site: `/deploy-pix-sites`.
Merger les deux commandes ?

[BUGFIX] Empêcher le run de /deploy-last-version sur une application autre que celle du repo Pix

---

scripts/publish.sh
scripts/release-pix-repo.sh

Voir #78. L'utilisation de sed n'étant pas idéale, chez repris la proposition de Jonathan.
Ne pas afficher les commandes bash dans la sortie du script
J'ai tenté d'utiliser le stockage des credentials de git, mais je ne vois pas comment l'utiliser tout en évitant d'afficher le token dans la sortie.
Faire une release et vérifier que les commandes bash ne sont plus affichées.

Ne pas afficher les commandes exécutés dans les scripts de publication pour ne pas afficher les tokens en prod

---

bin/www
config.js
run/controllers/deploy-sites.js
run/services/deploy.js
run/services/slack/commands.js

Depuis la PR https://github.com/1024pix/pix-site/pull/288 le site vitrine build les graphiques de statistiques à chaque déploiement. Seulement pour que ceux-ci soient à jour il faut qu'il y ait au moins un déploiement par mois.
Ajouter un CRON permettant de déployer une fois par mois Pix Site.
Ajouter la variable PIX_SITE_DEPLOY_SCHEDULE=0 0 1 * *

[FEAT] Ajout d'un CRON pour déployer Pix site tous les mois pour maintenir les statistiques à jour (PIX-2939).

---

build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
common/services/github.js
common/services/slack/view-submissions.js
run/services/slack/surfaces/modals/deploy-release/release-deployment-confirmation.js
test/unit/build/services/github_test.js

Quand on ajoute/enlève des variables d'env du fichier config.js, souvent il nous arrive d'oublier de faire la modification sur Scalingo recette/prod.
Si des variables ont été modifiées, alors lors d'une mise en prod/recette, une pop up slack nous en informera avant de confirmer la publication/le déploiement.
- pour une mise en recette
1. Aller sur  Slack API de Pix Bot BUILD Test  https://api.slack.com/apps/A01LUSH342F et récuéper le `Signing Secret` dans l'onglet **Basic information**  et le `bot user token` dans l'onglet **OAuth & permissions**. Mettre le tout dans le point .env
> SLACK_BOT_TOKEN= `Signing Secret`
> SLACK_SIGNING_SECRET=`bot user token`
2. Lancer 2 terminaux: 1 pour lancer votre api, et l'autre pour lancer `npx ngrok http 3000` ce qui va vous générer une url.
3. Cette …

[TECH] Notifier s'il y a eu des changements de variables d'environnement lors d'une mise en recette ou d'une mise en production.

---

scripts/common.sh

Lors de l'utilisation de Pix-UI nous avons constaté qu'il était difficile de comprendre les changements cassants d'une montée de version majeure. 
En comparant le fonctionnement des autres projets existant sur le web on a pu observer plusieurs manière de fonctionner : 
- soit pas de description sur les releases ou les tags 
- soit des descriptions pour chaques release et tags avec des catégories de changements (voir https://github.com/twbs/bootstrap/releases)
- soit un message indiquant de se référé au CHANGELOG (voir https://github.com/material-components/material-components-web/releases/tag/v13.0.0) 
Comme sur nos projets nous ne faisons pas de releases git mais juste des tags je propose de faire comme la dernière méthode, à savoir : indiquer dans les tags où trouver les changement …

[TECH] Documenter l'accès aux changements d'une release d'un projet Pix

---

scripts/release-pix-repo.sh

Lors de la release d'un projet PIX, on installait les packages npm de tout les sous dossiers. Ça ne sert a rien.
Supprimer l'étape, ce qui va accélérer la release.
Mais pourquoi c'était la ?
1. Faites nous confiance
2. Continuez a nous faire confiance

[BUGFIX] Suppression de l'étape d'installation des packages npm lors de la release

---

common/routes/slack.js
config.js
test/acceptance/common/slack_test.js

La vérification du webhook slack était dupliqué.
Supprimer la duplication
Vérifie que les nouveaux tests sont au vert

[CLEANUP] Supprimer de la duplication sur le webhook Slack

---

common/services/changelog.js
package.json

Nous avons deux dépendances directes a des librairie de date. Une seule suffit par rapport a nos besoins. Pour rester cohérent avec le dépot Pix, c'est dayjs qui est gardé. 
Des dépendances n'étaient pas non dans la partie dev.
Supprimer moment.js et utiliser dayjs. 
Déplacer les dépendances uniquement utilisé dans les tests en dépendances de dev.
1. Vérifier la génération du changelog
2. Vérifier que les dépendances de dev ne sont utilisées que dans les tests, en vérifiant que l'application fonctionne en RA

[CLEANUP] Supprimer l'utilisation de moment.js et nettoyage des dépendances

---

common/services/changelog.js
common/services/github.js
scripts/common.sh
scripts/get-pull-requests-to-release-in-prod.js
test/acceptance/scripts/publish_test.js
test/unit/common/services/changelog_test.js

En cas de hotfix, si des PRs sont mergé sur dev avant le hotfix (qui crée un tag sur une autre branche), le changelog de la version suivante ne contient pas ces PRs mergés.
Lors de la récupération du dernier tag sur le dépot, on ne prend en compte que ceux qui sont accessible depuis la branche courante. Comme le tag de hotfix ne peut pas être mergé sur dev, on est sur de ne pas avoir de mauvais cas.
Pour réussir a faire ça, on a du d'abord #100.
1. `npm run test`

[FEATURE] Génére correctement le changelog pour une release après une correction de release à chaud

---

test/acceptance/scripts/release-pix-repo_test.js
test/acceptance/scripts/script-helpers.js

Le script `release-pix-repo.sh` n'a pas de tests, ce qui n'est pas super rassurant lorque l'on veut mettre a jour le process de release.
Rajouter des tests, très similaire dans un premier temps a ceux de publish.sh #100 
1. Vérifier que les tests sont au vert

[CLEANUP] Ajout de tests unitaires sur le script release-pix-repo.sh

---

README.md
build/controllers/manifest.js
build/routes/manifest.js
run/controllers/manifest.js
run/routes/manifest.js
test/acceptance/build/manifest_test.js
test/acceptance/run/manifest_test.js

La configuration des applications slack Pix est manuelle. Il faut se baser sur ce qui se passe sur la production, mais nous n'avons pas de documentation de ce qui est fait.
Slack a rajouté le support des app manifest qui permettent de configurer une application slack d'un coup: https://api.slack.com/reference/manifests. 2 routes ont été rajouté pour retourner les manifest de build et de run.
Les manifest sont généré et mis à jour manuellement. Ca va bientôt changer.
1. Lancer pix-bot
2. Aller sur http://localhost:3000/run/manifest et regarder la config
3. Aller sur http://localhost:3000/build/manifest et regarder la config

[FEATURE] Générer le manifest pour configurer les applications slack

---

build/controllers/slack.js
build/routes/slack.js
common/controllers/slack.js
common/routes/slack.js
run/controllers/manifest.js
run/controllers/slack.js
run/routes/slack.js
test/acceptance/run/manifest_test.js

Les routes dans le dossier `common` sont mélangé entre la partie `build` et la partie `run` de pix-bot. Elles sont suffisamment spécifique pour être placés correctement dans l'arborescence de `pix-bot`.
Déplacer les routes `run` dans la partie `run`. Déplacer les routes `build` dans la partie `build`.
Il reste la route `/slack/interactive-endpoint` a séparer entre `build` et `run`. Cela va nécessiter des changements de routes. Ce sera pour la prochaine !
Tester les différentes routes.

[CLEANUP] Nettoyer les routes du module common

---

build/controllers/github.js

Des application scalingo sont toujours en review app automatique: pix-pro-review et pix-ui-review.
Rajouter le mapping correspondant dépot <-> application pour les faire déployer par pix-bot.

[FEATURE] Rajoute le déploiement des reviews app de pix-pro et de pix-ui

---

build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
common/services/slack/surfaces/modals/deploy-release/release-tag-selection.js
test/acceptance/common/slack_test.js

Le endpoint `/slack/interactive-endpoint` n'est pas testé actuellement
Rajouter des tests sur l'ensemble des cas.
Le split arrive très bientôt.
1. :green_circle:  tests

[CLEANUP] Ajout de tests sur le endpoint /slack/interactive-endpoint

---

common/services/changelog.js
common/services/github.js
scripts/common.sh
scripts/get-pull-requests-to-release-in-prod.js
test/acceptance/scripts/publish_test.js
test/acceptance/scripts/release-pix-repo_test.js
test/unit/common/services/changelog_test.js

#101 ne fonctionne pas car on clone le dépot avec `--depth 1` et les tests d'acceptance ne géraient pas bien ce cas
Revert en attendant de corriger correctement le problème
:green_circle:  tests

[REVERT] Génére correctement le changelog pour une release après une correction de release à chaud

---

README.md
build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
common/controllers/index.js
common/controllers/slack.js
common/routes/index.js
common/services/slack/shortcuts.js
common/services/slack/surfaces/modals/deploy-release/release-tag-selection.js
common/services/slack/surfaces/modals/publish-release/release-type-selection.js
common/services/slack/view-submissions.js
package-lock.json
package.json
run/services/slack/surfaces/modals/deploy-release/release-deployment-confirmation.js
test/acceptance/common/index_test.js
test/acceptance/common/slack_test.js

- Les modals slack sont écrite en dur et ne sont pas super claires.
- On a des identifiant de callback slack qui sont référencé a plusieurs endroits sans liaison claire dans le code.
- Utiliser `slack-block-builder`
- Utiliser des constantes pour référencer les callbacks
`slack-block-builder` a le bon gout de créer un lien vers le block builder de slack pour faire de la prévisualisation. Du coup j'ai rajouté une route /slackviews qui permet de visualiser cela.
Pas de changement dans les tests (ou vaiment mineur avec le `emoji: true` qui n'est plus nécessaire).

[CLEANUP] Refactoring des modals slack

---

common/services/changelog.js
common/services/github.js
scripts/common.sh
scripts/get-pull-requests-to-release-in-prod.js
scripts/publish.sh
scripts/release-pix-repo.sh
test/acceptance/scripts/publish_test.js
test/acceptance/scripts/release-pix-repo_test.js
test/unit/common/services/changelog_test.js

Reprise de #101 
En cas de hotfix, si des PRs sont mergé sur dev avant le hotfix (qui crée un tag sur une autre branche), le changelog de la version suivante ne contient pas ces PRs mergés.
On récupére la derniere version qui a été releaser via le package.json.
`npm run test`

[FEATURE] Génére correctement le changelog pour une release après une correction de release à chaud 

---

run/services/slack/commands.js
test/unit/run/services/slack/commands_test.js

Le déploiement en production des instances de pix-bot est cassé car nous avons renommé l'application scalingo de pix-bot build en pix-bot-build-production
Donner le nom correct de l'application a déployer sur scalingo
:green_circle:

[BUGFIX] Corrige le nom de l'application a déployer pour pix-bot-build

---

scripts/get-pull-requests-to-release-in-prod.js

La première release d'un repository ne fonctionne pas car on checkait `0.0.0 `au lieu de `v0.0.0`.
Corrigeait le code
:ok_hand:

[BUGFIX] Corrige la première release

---

common/services/releases.js
config.js
test/unit/common/services/releases_test.js

La configuration `PIX_APPS_TO_DEPLOY` que l'on récupère en variable d'environnement est en doublon avec `PIX_APPS`.
Utiliser `PIX_APPS` la on on utilisait `config.pixApps`.
:green_circle:

[CLEANUP] Supprime la config PIX_APPS_TO_DEPLOY

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/unit/run/services/slack/commands_test.js

Nous déployons métabase encore manuellement via scalingo
Avec la multiplication des environnements de metabase et par souci de standardisation, on rajoute une commande slash sur pix-bot
Pas de tag ni de changelog crée.
1. Sur le pix-bot de test taper /deploy-metabase

[FEATURE] Déploiement de metabase

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/unit/run/services/slack/commands_test.js

Actuellement, nous faisons les MEP de Pix Tutos directement via Scalingo, nous avons donc pas de tag associé à une version, ni de changelog. 
- Ajouter une commande gérant la création et le déploiement d'une release de Pix Tutos.

[TECH] Ajouter une commande de création et de déploiement de Pix Tutos (PIX-5127).

---

build/controllers/slack.js
build/manifest.js
test/acceptance/build/manifest_test.js

On souhaite créer un bot pour donner les rôles par tour lors d'un mob.
Créer un bot qui prend en entrée les noms des participants, celui-ci affichera ensuite les tours avec pour chaque tour les personnes assignées aux rôles de pilote et co-pilote.
L'installation d'un bot Slack c'est chouette.
Installer le bot en local et utiliser la commande `/mob @Pierre @Paul @Jacques`

[FEATURE] Créer une commande Slack pour donner les rôles par tour lors d'un mob

---

build/controllers/scalingo.js
build/controllers/slack.js
build/routes/scalingo.js
common/services/slack/surfaces/messages/post-message.js
config.js
test/integration/build/scalingo_test.js

On est notifié lors d'une erreur de déploiement sur la recette et la production mais pas sur l'intégration.
Créer un endpoint pour recevoir les webhooks Scalingo et envoyer un message Slack si une erreur de déploiement survient.
La solution proposée devrait être générique pour n'importe quel app Scalingo `osc-fr1`. Donc on peut l'ajouter sur l'intégration mais aussi sur n'importe quelle autre appli.
Dans les notifiers d'une app de test, essayer d'ajouter l'URL de cette RA 
> `https://pix-bot-review-pr135.osc-fr1.scalingo.io/build/scalingo/deploy-endpoint`
Exemple sur [pix-github-actions-test](https://dashboard.scalingo.com/apps/osc-fr1/pix-github-actions-test/settings/notifiers/no-90a7d2d2-1301-403f-81d4-fe005d79b970/edit).
Résultats attendus :
- Les déploiements en succès ne doivent rien …

[FEATURE] Être en capacité d'être notifié en cas d'erreur de deploiement

---

common/services/github.js
run/services/slack/view-submissions.js
test/acceptance/run/slack_test.js
test/test-helper.js
test/unit/build/services/github_test.js

Actuellement, lors de la MEP d'une release un message de modification du fichier de config peut-être affichée si un commit a modifié le fichier entre la release et le dernier commit sur dev.
Cependant, une MEP correspond à la mise en production d'une release créé pendant la MER. 
- Utiliser les bons commits pour déterminer sur un changement sur le fichier config a été fait.
- CI

[BUGFIX] Utiliser les commits entre les 2 releases pour afficher une notification de changement de config lors du déploiement

---

build/controllers/github.js
test/acceptance/build/github_test.js

Une PR déploie systématiquement une RA même pour des changements de CI ou de config qui ne peuvent pas être testés via une RA, ce qui peut engendrer des coûts supplémentaires inutiles.
Ajout d'un filtre sur le label pour ingorer le déploiement d'une RA 
Ajouter no-review-app dans les labels au moment de la rédaction d'une PR

[FEATURE] Eviter de déployer une RA si la PR contient le label `no-review-app`. 

---

.husky/pre-commit
.lintstagedrc.json
package-lock.json
package.json
server.js

Certains dévelopeurs souhaitent exécuter le lint à chaque commit, automatiquement, et que les erreurs soient corrigées automatiquement si besoin. D'autres non.
Voir https://github.com/1024pix/pix/pull/3982
Les tâches `npm` ont été triées par ordre alphabétique.
La configuration du lint n'est pas optimale (le fichier `server.js` était exclu sans raison), mais ne sera pas modifiée dans cette PR.
Installer le hook `npm run local:trigger-lint-on-commit`.
Ajouter un espace dans `server.js`.
Ajouter à l'indes et commiter.
Vérifier l'affichage du message .
```shell
⚠ lint-staged prevented an empty git commit.
Use the --allow-empty option to continue, or check your task configuration
husky - pre-commit hook exited with code 1 (error)
```

[TECH] Permettre de linter avec autofix avant chaque commit en local, si besoin.

---

common/controllers/index.js
common/models/ScalingoAppName.js
common/services/scalingo-client.js
common/services/slack/surfaces/user-infos/get-user-infos.js
config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/shortcuts.js
run/services/slack/surfaces/modals/scalingo-apps/application-creation-confirmation.js
run/services/slack/surfaces/modals/scalingo-apps/application-creation.js
run/services/slack/view-submissions.js
test/acceptance/run/manifest_test.js
test/acceptance/run/slack_test.js
test/unit/common/models/ScalingoAppName_test.js

L'ajout d'une app sur Scalingo demande de se connecter 2 fois pour la créer et l'assigner sur son compte perso.
Ajouter un raccourcis slack pour créer l'app et ajouter automatiquement l'utilisateur dans les collaborateurs.
Indiquer comment tester depuis le slack de test

[TECH] Créer une application Scalingo depuis Slack

---

.lintstagedrc.json
config.js
package.json
scripts/get-pull-requests-to-release-in-prod.js

La commande de lint cible des dossiers à la racine. 
Si un dossier est ajouté, il n'est pas linté.
Les fichiers à la racine ne sont pas lintés.
Linter l'ensemble des descendants de la racine.
Suppression d'une fonction non utilisée.
Introduire une violation dans un nouveau fichier et vérifier que `npm run lint` renvoie une code retour `1`

[TECH] Linter l'ensemble des fichiers.

---

run/manifest.js
test/acceptance/run/manifest_test.js

La longueur maximale est de 25 caractères, or elle en fait 32
La raboter
Serait-il possible d'avoir une validation dans la CI ?
Comparer le manifest avec celui de production (qui est lui valide)

[BUGFIX] Le nom du shortcut de création de l'application est trop long.

---

build/manifest.js
run/manifest.js
test/acceptance/build/manifest_test.js
test/acceptance/run/manifest_test.js

Il y a de plus en plus d'actions possible dans les applications Slack Run et Build.
Les PO utilisant principalement les actions de MEP et de MEP, leur label n'est plus affiché dans son intégralité et ralenti le processus
Faire démarrer le label par l'acronyme  MER ou MEP
Ca ne va pas tenir longtemps, l'ajout de nouvelles fonctionnalités va reléguer les MEP/MEP en fin de liste.
Une solution possible: isoler des actions dans une application dédiée.
Se rendre sur PixBot test, canal #tech-releases 
Vérifier que le libellé est correct (l'action va échouer, pas de déclenchement réel)

Mentionner MER/MEP au début du label de l'action de release

---

common/services/github.js
test/unit/build/services/github_test.js

Des PRs non prêtes à la review peuvent remonter lorsque l'on utilise la commande `/pr-pix` sur le Slack Pix.
Filtrer les PRs draft pour ne pas les retourner.
Petite mise à jour de test en même temps.
Comparer le résultat de `/pr-pix cross-team` sur le Slack de test et de prod

[FEATURE] Filtrer les PR draft sur la commande Slack /pr-pix 

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/acceptance/run/slashcommand_test.js
test/integration/run/services/slack/commands_test.js

Nous déployons gravitee actuellement via des git push. Mais nous voudrions avoir une façon standardisé de le faire.
Ajouter une slash command pour le faire.

[FEATURE] Déployer Gravitee

---

common/pre-response-handler.js
config.js
package-lock.json
package.json
sample.env
server.js
test/acceptance/common/index_test.js
test/test-helper.js

Si l'une des routes ne gère pas toutes les erreurs, le serveur Web sort en erreur.
De plus, la stacktrace affichée n'est pas lisible.
Catcher toute erreur non interceptée.
Répondre 500 à l'utilisateur avec un message d'erreur générique.
Tracer la stracktrace complète (la tronquer suivant les possibilités de Scalingo).
Création d'une route de test comme dans le monorepo, mais qui peut être supprimée si besoin.
Discussion sur https://1024pix.slack.com/archives/C658LDBAQ/p1665732852955529
La gestion des erreurs "attendues" (401, 400) n'est pas aussi claire que dans le monorepo (`DomainErrors`).
Configurer le log
```shell
scalingo --region osc-fr1 --app pix-bot-review-pr156 env-set MAX_LOG_LENGTH=1500
scalingo --region osc-fr1 --app pix-bot-review-pr156 restart
```
Provoquer une erreur …

[TECH] Gérer les erreurs inattendues

---

.github/workflows/prevent-fixup-commit.yaml

Si un rebase est en cours, le nom du commit porte le nom de l'action (ex: fixup!)
Utiliser une GHA pour empêcher le merge
Pousser un commit coupable et vérifier que le merge est désactivé

[TECH] Empêcher le merge si un rebase est en cours

---

package-lock.json

Pix-bot crashe lorsque l'API de scalingo échoue a scaler un container.
Pour ne pas envoyer d'exception en cas d'erreur, la dépendance `scalingo-review-app-manager` a été mise à jour.

[BUGFIX] Mise a jour de scalingo-review-app-manager

---

config.js

pix-datawarehouse-data vient d'être créé et n'est pas dans la liste des apps prise en charge pour la mise à jour de pix-db-replication
l'ajouter

Adding pix-datawarehouse-data to pix-db-replication app

---

build/controllers/github.js
common/pre-response-handler.js
test/acceptance/build/github_test.js
test/acceptance/common/index_test.js

Lorsque le client Scalingo renvoie une APIError, le code de Boom tente de modifier le champ data, qui n'a pas de setter. 
Cette tentative provoque un crash de l'application.
Catcher l'erreur sur la creation des RA et la renvoyer dans un format exploitable par Boom.
J'en ai profité pour simplifier le gestionnaire d'erreurs qui remplaçait ce que Boom fait déjà, et remplaçait les codes de retours par des 500, ce qui rendait les logs inexacts mais ne permettait pas d'empêcher les crash.
Lancer les tests

[BUGFIX] Corrige les crashs liés aux déploiements de Review Apps Scalingo

---

common/pre-response-handler.js

Les logs d'erreurs sont écrites sur plusieurs lignes de la sortie standard, empêchant son parsing
Stringify le log avant de l'envoyer
Lancer le test `test/acceptance/build/github_test.js` et vérifier que le log d'erreur est bien sur une seule ligne

:art: Ecrire les logs d'erreurs sur une ligne

---

config.js
test/integration/run/services/slack/commands_test.js

Le nom des applications Gravitee APIM de production ont changé.
On ne peut plus déployer via Pix-bot
Mettre a jour le noms des applications.

Mise à jour du nom des application Gravitee APIM

---

common/services/scalingo-client.js
config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/acceptance/run/slashcommand_test.js
test/integration/run/services/slack/commands_test.js
test/unit/common/services/scalingo-client_test.js

Le déploiement de Airflow en production nécessite de se connecter sur Scalingo, et ne peut être lancé que depuis une branche
Brancher le déploiement sur Slack via une slash command
Comme le repo est privé et qu'il est linké à Github via SCM, on peut utiliser l'API Scalingo correspondante pour déployer sans avoir à gérer d'authentification.
Lancer les tests, merger, déployer Pix-bot et déployer la version actuelle d'Airflow via Slack + Pix-bot

[TECH] Déployer Airflow en production depuis Slack

---

run/services/cdn.js
test/integration/run/services/cdn_test.js

Si l'invalidation du cache échoue, on ne n'a pas le détail de la réponse
La réponse du CDN
```json
{
"type" : "https://www.jhipster.tech/problem/problem-with-message",
"title" : "Bad Request",
"status" : 400,
"detail" : "JSON parse error: Unexpected character (',' (code 44)): expected a value; nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): expected a value\n at [Source: (PushbackInputStream); line: 1, column: 12]",
"path" : "/api/cache/invalidations",
"message" : "error.http.400"
}
```
Ce qui est loggé
```
Request failed with status code 500
```
Ajouter le message de réponse du CDN dans l'erreur
Pour obtenir le format de réponse de Baleen, j'ai invalidé le cache depuis l'UI et renvoyé un payload invalide
Vérifier que la CI passe

[TECH] Tracer le message d'erreur du CDN

---

common/models/ScalingoAppName.js
common/services/scalingo-client.js
config.js
run/services/slack/surfaces/modals/scalingo-apps/application-creation-confirmation.js
run/services/slack/view-submissions.js
test/acceptance/run/slack_test.js
test/integration/common/services/slack/view-submissions_test.js
test/integration/run/services/slack/view-submissions_test.js
test/test-helper.js
test/unit/common/services/scalingo-client_test.js

La création d'une application via Slack n'active pas les options attendues par Steampipe.
De plus, le nom de l'application est contrôlé, mais s'il n'est pas correct, le message d'erreur ne mentionne pas les règles attendues.
Ajouter automatiquement les options concernées.
Si le nom de l'application est incorrect, mentionner les règles attendues.
Ajout de tests manquants.
Configurer PixBotTest:
- supprimer le ngrok
- mettre à jour le manifeste depuis `https://pix-bot-review-pr168.osc-fr1.scalingo.io/run/manifest`
Dans `tech-releases`, saisir `scalingo`
Vérifier que l'application est créée avec:
- les logs routeurs
- le force_https à true

Créer une application Scalingo avec une configuration valide via Slack

---

.github/renovate.json

Désactivation des limites de Renovate pour tester le fonctionnement

:wrench: Désactiver les limites de PR de renovate

---

.depcheckrc
package-lock.json
package.json

Certaines dépendances utilisées ne sont pas installées directement.
Certaines dépendances installées directement ne sont pas utilisées.
Utiliser depcheck
Ajout d'une exception pour `lint-staged` qui est bien utilisée
Vérifier que la CI passe

[TECH] Prévenir les incohérences de dépendances

---

common/services/github.js

La rate-limit est atteint mais on ne sait pas pourquoi
Ajouter les appels Github dans les logs
Cela sera enlevé dès le problème trouvé
Effectuer un appel sur la RA depuis Slack de test
Vérifier que le message apparaît dans les logs

[TECH] Tracer les appels Github

---

.eslintrc.js

La configuration n'est pas la même que le monorepo: on ne vérifie pas la présence de tests exclusifs `only`, désactivés `skip`
Cela engendre de la confusion
Utiliser la même configuration du plugin eslint `mocha`
On pourrait partager la configuration pour éviter les désynchronisations.
Ajouter un test exclusif avec `only`.
Vérifier que la CI fail.

[TECH] Linter les tests de manière homogène

---

common/services/github.js
common/services/logger.js
package-lock.json
package.json
test/acceptance/run/slack_test.js
test/test-helper.js
test/unit/build/services/github_test.js
test/unit/common/services/logger_test.js

En cas d'erreur Github API (ex: rate_limit atteint), la stack d'erreur n'est pas tracée proprement.
Elle est sur plusieurs lignes au lieu d'une.
Utiliser un [hook](https://octokit.github.io/rest.js/v19#hooks) Octokit pour tracer l'erreur dans la sortie standard avec un champ qui permettre de la filtrer dans Datadog.
Exemple pour le rate-limit (mais au format chaîne de caractères).
``` json
{
"event": "github",
"response": "API rate limit exceeded for user ID 1. [rate reset in 8m48s]",
}
```
Je n'ai pas pu tester manuellement que Hapi, lorsqu'il intercepte l'erreur:
- renvoie une 500 à l'utilisateur;
- trace l'erreur sur une seule ligne;
Il y a un test auto générique là-dessus.
test/acceptance/common/index_test.js
Mais en posant un autre test auto sur `/run/slack/interactive-endpoint`, je …

[TECH] Tracer les erreurs Github

---

build/controllers/scalingo.js
common/services/logger.js
test/acceptance/build/scalingo_test.js
test/unit/common/services/logger_test.js

En cas de déploiement en erreur sur `pix-api-integration`, le message posté sur Slack est
`Failed deployement on the pix-api-integration application` 
Poster le message
`Failed deployment on the pix-api-integration application` 
Ajout d'un test d'acceptance
Vérifier que la CI passe

[TECH] Corriger l'orthographe de la notification de déploiement en erreur

---

build/templates/pull-request-messages/pix-editor.md
test/unit/build/controllers/pull-request-messages/pix-editor.md

Suite de https://github.com/1024pix/pix-bot/pull/205
Les corriger
On va y arriver à force.
Vérifier la CI

[BUGFIX] Les commentaires de PR ne sont toujours pas encore tout à fait corrects

---

build/controllers/github.js
test/unit/build/controllers/github_test.js
test/unit/build/controllers/pull-request-messages/pix-bot.md
test/unit/build/controllers/pull-request-messages/pix-editor.md

Les liens des reviews app dans les messages de Pix bot ne sont pas bon, ils contiennent une valeur fixe
Utiliser le numéro de PR dans le lien de l'application
La CI passe au vert.

[BUGFIX] Corrige le template d'urls pour les Review Apps.

---

build/templates/pull-request-messages/default.md
build/templates/pull-request-messages/pix-db-replication.md
build/templates/pull-request-messages/pix-editor.md
build/templates/pull-request-messages/pix-site.md
build/templates/pull-request-messages/pix.md
test/unit/build/controllers/pull-request-messages/pix-bot.md
test/unit/build/controllers/pull-request-messages/pix-db-replication.md
test/unit/build/controllers/pull-request-messages/pix-editor.md
test/unit/build/controllers/pull-request-messages/pix.md

Les liens dans les pull requests pour indiquer la review app et l'application scalingo utilisent du markdown avec nom 'ici'. En plus d'etre tout petit pour espèrer réussir a cliquer du premier coup, ce n'est pas descriptif de la cible.
Supprimer les liens ici qui n'apportent rien pour mettre directement l'URL cible. Une grande surface de clic disponible et on peut vérifier l'URL en bonus.
:(

[FEATURE] Change les liens vers les reviews app

---

build/controllers/github.js
build/templates/pull-request-messages/pix-data.md
test/unit/build/controllers/github_test.js
test/unit/build/controllers/pull-request-messages/pix-data.md

Les liens sont invalides.
Les corriger.
Merger, MEP, et ouvrir une PR sur `pix-data`.

[BUGFIX] Les liens vers l'application Airflow scalingo dans la PR sont invalides

---

.github/renovate.json

On veut:
- ouvrir les PR de montée de version aussi tôt que possible;
- les merger dès que les tests passent.
Or le preset existant ne le permet pas.
Utiliser un preset partagé.
Attendre le merge de https://github.com/1024pix/renovate-config/pull/1
Merger, réactiver Renovate et suivre le dashboard

Mettre à jour les dépendences aussi vite que possible

---

config.js
run/services/slack/commands.js
test/unit/run/services/slack/commands_test.js

Précédemment, pix-minimal qui est utilisé pour la partie open-source de pix et les test d'acceptance était déployé lors d'un merge sur dev. Cela pouvais déclencher des problèmes sur le dépot pix si une incompatibilité était introduite.
Déployer pix-lcms-minimal-production en même temps que la "vraie" production.
J'ai refactorer le déploiement de pix-bot qui faisait la même chose que ce dont j'avais  besoin. Un deploy sur 2 environnements séparé.
:green_circle:

[FEATURE] Déployer pix-lcms-minimal en même temps que la production

---

build/templates/pull-request-messages/pix-editor.md
test/unit/build/controllers/pull-request-messages/pix-editor.md

Le lien vers PixEditor est incorrect.
Ancien lien (exemple) : editor-pr87.review.pix.fr](https://editor-pr87.review.pix.fr/ 
Nouveau lien (exemple): https://pix-lcms-review-pr87.osc-fr1.scalingo.io

[BUGFIX] Corriger le lien vers PixEditor dans le message automatique envoyée au Reviews Apps

---

run/services/slack/commands.js
test/unit/run/services/slack/commands_test.js

Pour pix-ui et pix-ember-testing-library, le comportement actuel est de renvoyer une erreur si la version de bump de release n'est pas envoyée. Ce comportement est différent du comportement des autres applications, qui font un bump mineur par défaut.
Faire un bump mineur lorsque la version n'est pas précisée
🟢

:art: Faire un bump de version mineure par défaut

---

run/manifest.js
test/acceptance/run/manifest_test.js

Il existe une action Slack `Deploy last version of an app`.
Elle déploie:
- sur l'application passée en paramètre;
- la dernière release créée (pas forcément MEP), ex `v3.222.0` sur pix https://github.com/1024pix/pix/tags
Pour rappel, dans les autres actions Slack:
- Publier = MER;
- Déployer = MEP.
Le message est ambigü: Deploy = MEP alors qu'on peut effectuer cette action en dehors d'une application de production.
De plus, il est est en anglais alors que le reste est en français.
Du coup, les PO n'osent peut-être pas l'utiliser.
Le renommer en `Déployer sur cette application la dernière release publiée`
On garde "release publiée" = release en recette.
Et "déployer sur cette application" mentionne le déploiement Scalingo, pas le déploiement = MEP.
Relire

Corriger la suggestion de déploiement Slack

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js

L'application geoapi est actuellement reliée à la branche main
Retirer cette connexion automatique, et faire le déploiement via pix-bot
Les tests passent, merger et faire un déploiement via pix-bot

:sparkles: Déployer geoapi via Pix bot

---

build/services/eco-mode-service.js
config.js
sample.env

La configuration de l'ecoMode n'est pas claire.
On peut la confondre l'co-mode avec celle des autres tâches planifiées. :
- usage sendInBlue;
- pixSite.
De plus, elle n'est pas lue dans le `config.js`.
Renommer les variables d'environnement.
```
STOP_CRON_TIME => REVIEW_APP_STOP_SCHEDULE 
RESTART_CRON_TIME => REVIEW_APP_START_SCHEDULE
```
Penser à modifier les variables d'environnement sur les environnements aval (template RA, intégration, recette, production) avant de merger.
Alimenter les variables en RA
```
REVIEW_APP_START_SCHEDULE=0 0 8 * * 1-5
REVIEW_APP_STOP_SCHEDULE=0 0 19 * * 1-5
```
Redémarrer
Vérifier dans les logs le message
```
2022-12-30 14:41:51.080758679 +0100 CET [web-1] Started job stop-managed-review-apps with cron time "0 0 19 * * 1,2,3,4,5"
2022-12-30 …
```

Expliciter la configuration de l'ecoMode

---

config.js
package-lock.json
package.json
run/services/cdn.js
test/integration/run/services/cdn_test.js

L'invalidation de cache Baleen peut renvoyer des 500, Baleen recommande de toujours tenter de relancer la requête plusieurs fois.
Relancer la requête plusieurs fois (4 essais) pour faire passer l'invalidation de cache
les tests sont vert 
(On pourrait également rajouter les identifiants Baleen sur la RA et lancer une invalidation du cache sur une instance de test)

[TECH] :sparkles: Réessayer l'invalidation de cache en cas d'échec

---

build/templates/pull-request-messages/pix.md

L'url de review-app de pix1d n'est pas ajoutée dans le message de notification de création de review-app sur scalingo.
L'ajouter

:sparkles:  Ajout de l'URL des review-app de scalingo de pix1d    sur les messages github

---

build/controllers/github.js
common/services/scalingo-client.js
test/acceptance/build/github_test.js
test/unit/common/services/scalingo-client_test.js

Nous atteignons rapidement le "rate limiting" de github en utilisant l'auto deploy + les review apps de notre hébergeur
Utiliser nos outils de déploiements automatique via pix-bot pour optimiser l'utilisation des requêtes vers l'API github

[FEATURE] Au push sur une PR, on déploie nous même la review app

---

build/controllers/github.js
test/acceptance/build/github_test.js

Le code n'est pas déployé automatiquement quand une RA est créée, il ne l'est qu'après le premier push sur la PR
Déployer automatiquement la branche au moment de la création de la RA

Déployer le code à la création de la RA

---

build/services/slack/view-submissions.js
common/services/releases.js
index.js
run/controllers/deploy-sites.js
run/services/deploy.js
run/services/slack/commands.js
scripts/release-pix-repo.sh
test/acceptance/scripts/release-pix-repo_test.js
test/unit/common/services/releases_test.js
test/unit/run/services/slack/commands_test.js

Lorsque nous créons une nouvelle release, la version à déployer est récupérée depuis l'API de GitHub plutôt que d'utiliser la version tout juste créée, ce qui peut provoquer des incohérences (release créée mais autre version déployée)
Utiliser la version qui vient d'être release
Vérifier la CI

[TECH] Utiliser la version de release qui vient d'être crée plutôt que d'appeler l'API Github

---

build/controllers/github.js
test/acceptance/build/github_test.js

Lors de la cloture d'une PR, un dernier force push peut générer des erreurs
Utiliser le `state` : `open` de l'évènement `Synchronize` pour limiter l'utilisation aux PR ouvertes

Prendre en compte le status ouvert d'une PR lors d'une synchro / dépoloiement de RA 

---

build/templates/pull-request-messages/pix.md

Certaines PR ont maintenant besoin des URL de la RA Pix Orga sur .org et de la RA Pix Certif sur .org.
Voici quelques exemples de telles PR : 
* Pix Orga .org https://github.com/1024pix/pix/pull/5991
* Pix Certif .org https://github.com/1024pix/pix/pull/5948
Ajouter 2 nouvelles lignes pour les 2 nouveaux URL à la template de PR pour le monorepo.
RAS
Je ne sais pas.

[FEATURE] Ajouter les URL de la RA Orga sur .org et de la RA Certif sur .org

---

build/templates/pull-request-messages/pix-tutos.md

Actuellement Pix tutos, utilise le router nginx pour avoir des urls sous la forme `https://tutos-pr141.review.pix.fr/`. 
Sous Nuxt 3, des appels à `/api` se font et le router ne le permet pas pour les apps autres que celles du monorepo.
Comme ce routeur est pas nécessaire, je propose de ne pas l'utiliser et utiliser l'url fourni par Scalingo directement.
Pour cela, nous ajoutons un template de commentaires sur les pull requests de Pix Tutos avec l'url fourni par Scalingo

[TECH] Ajout d'un template de commentaire pour Pix Tutos

---

.eslintrc.js
build/controllers/scalingo.js
build/controllers/slack.js
build/services/eco-mode-service.js
build/services/google-sheet.js
common/pre-response-handler.js
common/services/cron-job.js
common/services/github.js
common/services/logger.js
common/services/releases.js
common/services/scalingo-client.js
common/services/slack/security.js
common/services/slack/surfaces/messages/post-message.js
common/services/slack/surfaces/user-infos/get-user-infos.js
index.js
run/controllers/slack.js
run/services/cdn.js
scripts/get-pull-requests-to-release-in-prod.js
test/acceptance/build/scalingo_test.js
test/unit/build/services/github_test.js
test/unit/common/models/ScalingoAppName_test.js
test/unit/common/services/logger_test.js

Certains logs sont effectués avec la console alors qu'un logger est disponible. 
Cela ne facilite pas la maintenance.
Utilisr le logger.
🟢

[TECH] Tracer avec le logger dédié partout (PIX-8176)

---

build/templates/pull-request-messages/pix.md

L'url vers la review app de Pix1d commence par `pix1d-xxx` au lieu de `1d-xxx`
Mettre à jour le template de message de PR envoyé par Pixbot
aucune
Merger cette PR et ouvrir une PR sur le mono-repo

[BUGFIX] Correction de l'url de Pix1d dans les commentaires de PR (PIX-8336)

---

test/unit/common/services/releases_test.js

Les tests de déploiement:
- testent plusieurs choses à la fois
- sont incomplets
Diviser le test en deux.
Ajouter un test sur le code non couvert
Muter l'implémentation et vérifier que le test échoue

[TECH] Améliorer le test du déploiement du monorepo

---

README.md
build/controllers/github.js
build/templates/pull-request-messages/pix-4pix.md

Les review-app de Pix4Pix ne sont pas activées.
Les activer.
Pour qu'elles soient accessibles, [cette PR](https://github.com/1024pix/pix-review-router/pull/13) devra être mergée
Merger et ouvrir une PR sur le repository Gihtub.
Vérifier qu'une review-pp est créée dans Scalingo.
Vérifier que les liens postés dans la PR mènent à l'application.

Activer les review-app de l'application Pix4Pix

---

common/models/PullRequestGroupFactory.js
common/models/Tags.js
common/services/changelog.js
test/unit/common/models/PullRequestGroupFactory_test.js
test/unit/common/models/Tags_test.js
test/unit/common/services/changelog_test.js

Avec Renovate nous créons des PRs préfixées par le tag `BUMP`. Pour le moment elles se retrouvent dans un groupe du changelog nommé "Autre".
On propose d'ajouter un tag BUMP pour générer une section `:arrow_up: Montée de version` en bas du changelog (juste avant "Autre").
La CI passe

[FEATURE] Ajoute le suport du tag `BUMP` en préfixe de PR

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/unit/run/services/slack/commands_test.js

Il n'y a pas de commande pour déployer pix-api-data
L'ajouter
L'app pix-api-data-production n'existe pas encore mais cette PR est en prévision des MEP de cette app.

Ajout d'une commande slack de déploiement pour pix-api-data

---

build/controllers/github.js
build/templates/pull-request-messages/pix.md
test/acceptance/build/github_test.js

Suite à https://github.com/1024pix/pix/pull/6841, l'application `audit-logger` migre dans le projet du monorepo. On souhaite que son cycle de déploiement soit identique au reste du monorepo.
Faire la configuration pour avoir des ra automatiques pour audit-logger
🟢

[TECH] :sparkles: Ajouter l'application audit-logger dans la configuration des RA du monorepo 

---

README.md
build/controllers/github.js
config.js
package.json
test/acceptance/build/github_test.js

Le déploiement effectué par Scalingo en auto-deploy épuise notre quota Github.
Ce problème a été remonté, mais n'a pas été corrigé.
Déployer à leur place en pushant une archive.
On va faire un ticket après pour rendre le code testable en intégration et unitairement.
Merger la PR.

[FEATURE] Déployer l'intégration du monorepo avec Pix Bot (PIX-8933)

---

build/controllers/github.js
common/services/scalingo-client.js
config.js
test/acceptance/build/github_test.js
test/unit/common/services/scalingo-client_test.js

Dans le cas ou les variables d'environnement configurant le client scalingo ne serait pas définies, Pix bot renvoie une erreur sans l'expliciter
Gérer le cas ou les identifiants utilisés ne sont pas définis.
🟢

[BUGFIX] Vérifier que la configuration Scalingo est fournie avant l'appel d'authentification

---

config.js
test/unit/common/services/releases_test.js

Audit-logger n'est pas déployer automatiquement en prod / recette.
L'ajouter dans les PIX_APPS dans le config.js afin qu'il soit pris en compte.
Vérifier que le déploiement se fait correctement après la prochaine MER / MEP une fois que cette PR est mergée

Déployer audit-logger automatiquement lors de MER / MEP

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

Tout le code de gestion des webhook Github n'est testé qu'en acceptance.
Les tests sont long à écrire, à lire, à exécuter.
Rajouter des tests unitaires
🟢

[TECH] Tester unitairement la gestion des appels webhook de Github

---

common/services/github.js
package-lock.json
package.json

Le client Github Octokit utilise par défaut `fetch` natif, qui n'est pas encore compatible avec Nock, et qui nous empêche ainsi de passer en node18 sans devoir passer des flags spécifiques de désactivation.
Forcer l'usage de la lib `node-fetch` (en v2 car la v3 n'est compatible qu'ESM) au client Octokit le temps que nock puisse ajouter le support `fetch`
Une issue est en cours sur le projet Nock pour prendre en compte aussi le fetch natif : https://www.github.com/nock/nock/issues/2397
Octokit propose d'utiliser node-fetch au besoin : https://github.com/octokit/octokit.js/#fetch-missing
Sur node16: 🟢
Passer à node18 en local et valider que les tests passent correctement.

[TECH] Forcer l'utilisation de node-fetch par Octokit

---

common/services/scalingo-client.js
config.js
index.js
run/services/task-scheduler.js
run/services/tasks.js
run/services/tasks/autoscale-web.js
sample.env
test/integration/run/services/task-scheduler_test.js
test/integration/run/services/tasks/autoscale-web_test.js
test/integration/run/services/tasks_test.js
test/unit/common/services/scalingo-client_test.js

L'autoscaler de Scalingo peut mettre du temps à provisionner des containers, un pic de connexion peut donc générer des erreurs.
Cependant, nous connaissons à peu près les horaires des possibles pics de connexion. 
Ajouter un cron pour configurer automatiquement l'autoscaler à des heures définies en utilisant un service de lancement de tâches :
- mise à jour du **ScalingoClient** en ajoutant la fonction pour configurer l'autoscale pour une app donnée et lui passant des valeurs min et max pour le nombre de containers web à provisionner
- création d'un planificateur de tâches pouvant lancer une liste de tâches à planifier
- création d'une tâche pour l'autoscale des containers web
- création d'une liste de 2 tâches, **morningAutoScale** et **eveningAutoScale**
- chaque peut être paramétrée …

[TECH] Ajout d'un job pour configurer automatiquement l'autoscaler d'applications sur Scalingo (PIX-8638)

---

run/services/tasks/autoscale-web.js
test/integration/run/services/tasks/autoscale-web_test.js

Nous ne savons quand l'autoscaler est vraiment démarré.
Nous avons ajouté des logs juste avant que la tâche démarre.
🟢

[TECH] Ajout de logs quand l'autoscaler démarre

---

build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
build/services/slack/view-submissions.js
common/services/github.js
test/acceptance/build/slack_test.js
test/unit/build/services/github_test.js

Une modification du fichier de configuration API ne veut pas forcément dire qu'un variables d'environnement doive être modifiée.
Ajouter le lien sur la diff pour consulter plus facilement le fichier.
On pourra faire mieux ensuite et détecter les variables d'environnemment avec  `process.env`.
Merger

[FEATURE] Ajouter un lien vers la diff lors de la création de la release

---

build/controllers/scalingo.js
build/controllers/slack.js
common/http-agent.js
common/services/slack/surfaces/messages/post-message.js
run/services/slack/commands.js
run/services/slack/view-submissions.js
test/integration/build/scalingo_test.js
test/unit/common/http-agent_test.js
test/unit/common/services/slack/surfaces/messages/post-message_test.js

Le code qui envoie un message sur slack n'est pas testé. 
Ce code laisse passer des erreurs.
Implémenter un client HTTP utilisant Axios gérant les erreurs.
Utiliser ce client HTTP dans la méthode `postMessage()`.
🟢

[TECH] Utiliser un client HTTP pour communiquer avec Slack

---

build/services/slack/view-submissions.js
test/acceptance/build/slack_test.js

Lors du workflow Slack de MEP/PE, seul les gens ayant déclenché la modale sont prévenus des changements sur le fichier api/lib/config.js 
Prévenir l'ensemble des personnes sur le channel de release de la modification du fichier, en envoyant un message.
Apportant le détail des PR concernées.
Utiliser Slack de test, relié à l'application Scalingo `pix-bot-integration`

[FEATURE] :sparkles: Envoyer un message sur slack en cas de changements sur le fichier config.js

---

build/services/slack/view-submissions.js
common/services/slack/surfaces/messages/post-message.js
test/acceptance/build/slack_test.js
test/unit/common/services/slack/surfaces/messages/post-message_test.js

Le message actuel n'apporte aucune information utile à l'identification des changements sur le fichier de config. 
Modifier le message pour ajouter l'url du diff GitHub. 
On journalise également les erreurs de l'API slack. 
Configurer la review app avec les tokens du slack de test, et sur le projet GitHub de test. Créer une Release via l'action

[BUGFIX] Corriger le message envoyé sur slack lors de changements du fichier config.js

---

sample.env

La variable d'environnement  `BALEEN_APP_NAMESPACES`, si non renseignée, cause un message d'erreur dans les tests.
```
2) Acceptance | Scripts | release-pix-repo.sh
Update package version, generate changelog, commit, tag and push:
Command failed: /home/octo-topi/Documents/Octo/Missions/Pix/repositories/pix-bot/scripts/release-pix-repo.sh 1024pix pix-bot-publish-test minor dev file:///tmp/clean-repositorypim3bh
Cloning into '/tmp/tmp.JgEaRnE8U9'...
undefined:1
__CHANGE_ME__
^
```
Or celui-ci ne mentionne pas la variable d'environnement.
Propose une valeur dans le `sample.env` qui soit un JSON valide
On pourrait intercepter l'erreur et ajouter un message.
Ou dire dans le `sample.env` qui si elle n'est pas modifiée, les tests sortent en erreur.
Ou modifier la configuration des tests.
```
cp …
```

Empêcher le crash de l'API en cas de configuration incorrecte

---

common/services/logger.js
sample.env
test/unit/build/services/github_test.js
test/unit/common/services/logger_test.js

Le compte-rendu des tests en local est illisible
Désactiver le log pendant les tests
Cela n'a pas pu être fait partout, notamment dans les scripts bash où il n'y a pas d'injection de dépendance
`npm run test`

Ne pas tracer durant les tests

---

build/services/slack/view-submissions.js
common/services/github.js
test/acceptance/build/slack_test.js
test/unit/build/services/github_test.js

Lorsqu'un changement de config a été effectuée lors d'une mise en recette, un message est désormais envoyé sur tech release. Cependant nous n'affichons que le lien vers la diff de version.
Pour améliorer le processus, nous allons afficher dans le message et le label de la team concernée et le lien vers la PR associée au changement de config
Créer deux PR qui modifient la config sur https://github.com/1024pix/pix-renovate-test.
Lancer l'action sur le slack Pix bot test.

[TECH] Afficher le label de la team concernée et le lien vers la PR associée au changement de config

---

common/services/github.js
test/acceptance/build/slack_test.js
test/test-helper.js
test/unit/build/services/github_test.js

Suite a une migration sur l'API de Pix le fichier de config a ete deplace
https://github.com/1024pix/pix/pull/7140
On ne peut donc plus avoir d'alerte lorsque ce fichier est modifie
Mettre a jour son chemin
A merger si possible au plus tot apres la MEP de https://github.com/1024pix/pix/pull/7140
Modifier config.js sur l'API et s'assurer que un warning est remonte (pas reproductible avant la MEP)

[TECH] Mettre a jour le chemin de config.js

---

build/controllers/github.js
common/services/logger.js
common/services/scalingo-client.js
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js
test/unit/common/services/logger_test.js
test/unit/common/services/scalingo-client_test.js

La création de RA ne fonctionne pas toujours, cela pose un problème lors du déploiement sur Scalingo suite à l'évènement github de synchronisation de PR.
Vérifier si la RA existe avant de la déployer et ajouter la création de celle-ci lors de l'évènement github de synchronisation dans le cas contraire.
- Enrichissement du logger pour un suivi plus facile du monitoring 
- On en profite pour faire une refactorisation des logs 
Tests ✅

[TECH] Vérifier si une RA existe avant de la créer

---

build/controllers/github.js
build/templates/pull-request-messages/pix-epreuves.md

Les RA sur pix-epreuves sont déployées automatiquement via github ce qui nous rend dépendant de la réussite de la CI.
Utiliser pix-bot pour déployer l'application.
RAS
IDK

[TECH]  Permettre la création de review app sur pix-epreuves.

---

common/services/github.js
common/services/releases.js
common/services/scalingo-client.js

Lors du déploiement d'un repo, on appelle la fonction `logger.info` avec comme seul argument le message que l'on souhaite logguer.
Comme la fonction attend un objet dans lequel on peut injecter l'objet log contenant lui-même la fonction `info`, cela pour conséquence de lever une erreur.
On corrige l'appel de la fonction en passant en argument un objet contenant la propriété `message`.
On en profite pour corriger tous les appels de `logger.info` et `logger.error`.
Appeler la route `/deploy-sites`.

[BUGFIX] Corrige l'utilisation de `logger.info` lors du déploiement d'un repo.

---

common/services/logger.js
common/services/releases.js
common/services/scalingo-client.js
test/unit/common/services/logger_test.js

Le logger ok n'existe pas sur la console. Suite à https://github.com/1024pix/pix-bot/pull/351, on a commencé à l'utiliser (ce qui ne fonctionne pas)
Supprimer complètement toute référence à ce logger
🟢

[TECH] Utiliser le logger info à la place du logger ok qui n'existe pas

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

Reverts 1024pix/pix-bot#363
La RA n'est pas créé automatiquement lorsque la PR passe de DRAFT à pas DRAFT. 
De plus, il serait intéressant de mettre en place un « forçage » via le tag « no-review-app » ou un autre tag pour forcer le déploiement de la RA

Revert "[FEATURE] Ne pas créer de RA quand la PR est en draft (PIX-9921)"

---

config.js

L'application `pix-1d-integration` a été renommée en `pix-junior-integration` ce qui entraine l'échec du déploiement continue depuis la branche `dev`.
On renomme les dernières occurrences de `pix-1d` en `pix-junior`.
RAS
Une CI verte et go !

[BUGFIX] Gère le renommage de l'application pix-1d-integration.

---

build/controllers/github.js

Il n'y a pas de RA pour pix-api-data alors que c'est pratique :) 
Ajouter la configuration nécessaire, on se base sur l'integration car nous n'avons pas la nécessité d'avoir un template dédié

[FEATURE] Activer les RA pour pix-api-data

---

build/controllers/github.js
build/templates/pull-request-messages/pix-api-data-pix.md

Les RA pour pix-api-data-pix ne sont pas gérées par pix-bot mais directement par Scalingo (ce qui est une mauvaise pratique)
Ajouter pix-api-data-pix et inclure un template de PR

[FEATURE] Activer les RA pour pix-api-data-pix

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/acceptance/run/slashcommand_test.js
test/integration/run/services/slack/commands_test.js

Souhait d'ajouter une commande slack pour le déploiement de pix-data-api-pix

[FEATURE] Ajout d'une commande slack pour déploiement de pix-data-api-pix (PIX-13714)

---

build/controllers/github.js
config.js
sample.env
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js
test/unit/common/models/ScalingoAppName_test.js

Actuellement, plusieurs étapes manuelles persistent sur certains repository comme la création de release via l'interface de GitHub et le déploiement depuis une commande Slack. Les deux sont toujours suivies, cela n'a donc pas d'intérêt d'être manuel. 
Dans cette PR, nous nous concentrons sur la deuxième étape qui est de remplacer la commande Slack par l'utilisation des Webhooks GitHub. 
GitHub appelle déjà Pix Bot à chaque création de release mais Pix Bot ne fait rien de cet évènement. Ici, nous ajoutons donc la logique pour que Pix Bot puisse déployer les apps associées au repo qui a une nouvelle release. 
Cette PR vient avec l'ajout d'une nouvelle variable d'environnement. `REPO_APP_NAMES_MAPPING` qui a pour but d'éviter les PRs pour ajouter une fonctionnalité pour un nouveau repository …

[FEATURE] Permettre le déploiement dès la création d'une release (PIX-13870).

---

config.js

Si la variable `REPO_APP_NAMES_MAPPING` n'est pas configurée alors des 500 ont lieu.
Ajouter une valeur par défaut

[BUGFIX] Eviter les 500 sur l'appel /github/webhook. 

---

run/controllers/github.js
test/acceptance/run/github_test.js
test/unit/run/controllers/github_test.js

Actuellement, le webhook GitHub fonctionne uniquement pour les apps qui est lié à un repository (cf: [Source Code Management - Scalingo](https://doc.scalingo.com/platform/app/scm-integration)). Cependant, nous souhaitons pas lier nos apps à des dépots GitHub.
Permettre le déploiement sans que le repo soit lié à l'application Scalingo

[FEATURE] Déployer les apps grâce au webhook GitHub sans que le repository soit lié dans Scalingo.

---

build/controllers/github.js
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js

Le controller GitHub qui est chargé de gérer les webhooks provenant de GitHub est compliqué à la lecture car le code est presque semblable, mais n'est pas unifié.
Unifier le code pour la gestion des RA des Pull Requests.
- CI OK

[TECH] Refactorer le controller GitHub

---

build/controllers/github.js
common/services/scalingo-client.js
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js
test/unit/common/services/scalingo-client_test.js

Scalingo ne clôture pas automatiquement toutes les reviews apps lorsqu'une PR est clôturée/mergée.
Ajouter dans Pix Bot la capacité de clôturer une review app.
```
curl -X POST -H "x-github-event: pull_request" -H "content-type: application/json" http://localhost:3000/github/webhook -d '{"action":"closed","number":83,"pull_request":{"state":"closed","head":{"repo":{"name":"pix-tutos","fork":false}}}}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /github/webhook HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> x-github-event: pull_request
> content-type: application/json
> Content-Length: 115
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK …
```

[FEATURE] Clôturer les review apps depuis Pix Bot (PIX-14712)

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

Lorsqu'une PR d'un repo non managé par Pix Bot est clôturée ou mergée, Pix Bot renvoie une erreur 500.
- Ne pas tenter de clôturer une RA pour un repo qui n'est pas géré par Pix Bot.

[BUGFIX] Corriger la suppression des RA pour les repo non gérés par Pix Bot (PIX-14712)

---

build/services/eco-mode-service.js

Par réflexe, nous ajoutons des `async`/`await` un peu partout, mais certains ne servent à rien.
Suppression d'un `await` inutile.

[TECH] :recycle:  Suppression d'un `await` inutile

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/acceptance/run/slashcommand_test.js
test/integration/run/services/slack/commands_test.js

L'application `pix-data-api-pix-production` a été renommée en `pix-api-to-pg-production`. Cependant, le endpoint de déploiement concerne encore l'ancienne application qui n'existe plus.
- Renommer le endpoint `/deploy-pix-data-api-pix` en `/deploy-pix-api-to-pg`
- Déployer l'application `pix-api-to-pg-production` plutôt que `pix-data-api-pix-production`

[TECH] Renommer le endpoint /deploy-pix-data-api-pix

---

build/repository/review-app-repository.js
test/integration/build/repository/review-app-repository_test.js

Il existe actuellement une contrainte d'unicité sur le nom d'une RA dans la table `review-apps`. Cependant, il arrive parfois qu'une PR nécessite d'être fermée puis rouverte lorsque les addons n'ont pas été bien provisionnés lors du déploiement comme pour la PR [suivante](https://github.com/1024pix/pix/pull/10540). Aujourd'hui, cela cause une erreur car la contrainte est violée.    
Merger une RA plutôt que de renvoyer une erreur quand elle est recrée

[BUGFIX] Mettre à jour le statut d'une RA quand elle est recréée

---

common/services/scalingo-client.js
test/unit/common/services/scalingo-client_test.js

Aujourd'hui, Pix Bot est capable de supprimer les RA dont le nom contient "-review-pr". Cependant, certaines RA comme pix-data-api-pix-integration-pr17 ne sont pas issues d'une application "template" contenant le nom "review".
Utiliser une Regex afin d'identifier les RA

[FEAT] Permettre la suppression de RA n'ayant pas "-review-pr" dans leur nom

---

build/controllers/github.js
test/acceptance/build/github_test.js
test/acceptance/scripts/publish_test.js
test/acceptance/scripts/release-pix-repo_test.js

supprimer les RA lors de l'ajout du label no-review-app
Les RAs ne sont pas recréées lors de l'ajout du label. Pour cela il faudra fermer et réouvrir la PR.
Le webhook github ne permet pas pas d'avoir un événement lors du retrait du label no-review-app uniquement.
On a un évènement unlabeled et la liste des labels actuels.

[FEATURE] Pix-15117 supprimer les RA lors de l'ajout du label no-review-app

---

build/controllers/github.js
build/templates/pull-request-messages/pix-exploit.md

Actuellement, Scalingo déploie automatiquement les review apps du projet pix-exploit ce qui n'est pas conseillé à cause du risque de sur utilisation du token github.
Ajouter le déploiement des reviews app de pix-exploit.

[TECH] Ajouter le déploiement des reviews app de pix-exploit

---

config.js
run/controllers/security.js
run/routes/security.js
run/services/cdn.js
sample.env
server.js
test/acceptance/run/security_test.js
test/integration/run/services/cdn_test.js
test/unit/run/controllers/security_test.js

Il est parfois nécessaire de bloquer une ou plusieurs ip/ja3 dans Baleen. Cependant, cette opération doit actuellement être faite manuellement.
Ajouter un webhook permettant, depuis Datadog, d'ajouter une ou des règles de blocage d'ip et/ou ja3.

[FEAT] Ajouter un webhook permettant de bloquer une ip et/ou un ja3 depuis Baleen

---

build/services/merge-queue.js
common/services/github.js
test/unit/build/services/github_test.js
test/unit/run/services/merge-queue_test.js

Le dispatch du workflow n'utilisait pas octokit et ne passait pas de token d'auth ce qui avait pour conséquence de ne pas lancer de workflow
Utiliser la lib octokit pour lancer le worflow
ras
on testera en mergeant la PR

[BUGFIX] Utiliser octokit pour trigger le dispatch worfklow event

---

build/controllers/merge.js
test/acceptance/build/merge_test.js
test/unit/build/controllers/merge_test.js

La fonction mergeQueue est mal importée dans le controller
Corriger l'import et ajouter un test d'acceptance

[BUGFIX] Corriger l'injection de dépendance dans le controller merge

---

build/controllers/github.js
build/controllers/merge.js
build/repositories/pull-request-repository.js
build/services/merge-queue.js
test/acceptance/build/github_test.js
test/integration/build/repositories/pull-request-repository_test.js
test/unit/build/controllers/github_test.js
test/unit/build/controllers/merge_test.js
test/unit/run/services/merge-queue_test.js

Actuellement, nous avons une merge queue pour tous les repos de Pix, ce qui peut faire attendre les repos avec peu de PR pour rien car les PR pourraient être mergée de suite. 
Faire une merge queue par repository.

[FEATURE] Avoir une merge queue par repository

---

build/controllers/github.js
common/services/github.js
test/unit/build/controllers/github_test.js
test/unit/build/services/github_test.js

Lorsqu'on rebase et relance les check d'un PR, il arrive q'un des checks echouent (flaky / problème de déploiement).
On supprime alors la PR de la mergequeue. 
Cela implique de devoir à nouveau passer sur la PR pour supprimer puis ajouter à nouveau le tag `🚀 Ready to Merge` 
Lorsqu'on recoit un évenement `check_suite` et que le statut est `success` on ajoute de nouveau la PR dans la mergequeue si elle contient le label `:rocket: Ready to Merge`
RAS

[FEATURE] ajoute à la mergequeue lorsque la check_suite se met à jour

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

Le payload attendu lors d'un appel du webhook github pour l'action `check_suite` n'est pas conforme à [la documentation.](https://docs.github.com/en/webhooks/webhook-events-and-payloads#check_suite), ce qui provoque des erreurs 500.
Utiliser le bon format

[BUGFIX] Corriger le payload attendu lors d'un évènement check_suite.

---

build/controllers/github.js
test/acceptance/build/github_test.js

Actuellement, nous avons des 500 dans le controller github dans le if correspondant aux events `check_suite`, car Hapi.js souhaite que le controller retourne quelque chose. 
Ajouter les retours manquants
D'autres conditions fonctionnent mais utilisent le return `Ignoring action`, ce qui n'est pas génial non plus;

[BUGFIX] Eviter les 500 dans le controller GitHub

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

Actuellement, nous ne gérons pas le cas où la check_suite n'est pas liée à une PR comme par exemple les tests sur main, ce qui provoque des 500.
Ajouter un early return pour ce cas.

[BUGFIX] Gérer le cas où la check_suite n'est pas liée à une PR.

---

build/repositories/pull-request-repository.js
test/integration/build/repositories/pull-request-repository_test.js

Actuellement, lorsque la PR est déjà dans la merge queue et qu'on essaie de l'ajouter à nouveau, cela se passe pas bien. 
Faire en sorte que le repo ne jette pas d'erreur

[BUGFIX] Ne pas jetter d'erreur quand la PR est déjà dans la merge queue.

---

build/controllers/github.js
build/controllers/merge.js
build/services/merge-queue.js
test/unit/build/controllers/github_test.js
test/unit/build/controllers/merge_test.js
test/unit/run/services/merge-queue_test.js

La merge queue fonctionne uniquement si au préalable nous avons ajouté ou supprimé une PR, pour éviter la charge mentale, nous pouvons tout déléguer au service de merge.
Déléguer l'ajout et la suppression de PR au service de merge.

[TECH] Simplifier l'usage de la merge queue

---

build/repositories/pull-request-repository.js
build/services/merge-queue.js
common/services/github.js
test/acceptance/build/github_test.js
test/integration/build/repositories/pull-request-repository_test.js
test/unit/build/services/github_test.js
test/unit/run/services/merge-queue_test.js

Actuellement, depuis la gestion de la merge queue par Pix Bot, nous n'avons pas d'information visuelle sur l'état d'avancement de la PR.
Ajouter un check_status qui se met à jour pour indiquer l'avancement de la PR dans la file, et rassurer les développeurs.## :gift: Proposition

[FEATURE] Indiquer dans les PRs qu'elles sont en cours de merge

---

build/controllers/github.js
build/controllers/merge.js
build/services/merge-queue.js
common/services/github.js
test/acceptance/build/github_test.js
test/acceptance/build/merge_test.js
test/unit/build/controllers/github_test.js
test/unit/build/controllers/merge_test.js
test/unit/build/services/github_test.js
test/unit/run/services/merge-queue_test.js

Actuellement, le commit status ne se met pas à jour lorsque la pr est mergée, en échec ou autres.
Mettre à jour le status

[FEATURE] Mettre à jour le check de commit lorsqu'une PR n'est plus managée par la merge queue

---

build/repositories/pull-request-repository.js
build/services/merge-queue.js
test/integration/build/repositories/pull-request-repository_test.js
test/unit/run/services/merge-queue_test.js

Actuellement, certaines conditions peut nous amener à ajouter un check commit sur une PR alors qu'elle n'a jamais eu la volonté d'être mergée. 
Ajouter une vérification avant `unmanage` une PR.

[BUGFIX] Ajouter des checks de commit à propos du status de merge uniquement sur les PR dans la file de merge.

---

common/services/slack/surfaces/messages/post-message.js
common/services/slack/surfaces/messages/update-message.js
config.js
run/controllers/applications.js
run/controllers/security.js
run/controllers/slack.js
run/models/AutomaticRule.js
run/services/cdn.js
run/services/slack/block-actions.js
sample.env
test/acceptance/run/security_test.js
test/acceptance/run/slack_test.js
test/integration/run/services/cdn_test.js
test/unit/common/services/slack/surfaces/messages/post-message_test.js
test/unit/common/services/slack/surfaces/messages/update-message_test.js
test/unit/run/services/slack/block-actions_test.js

Actuellement, il existe une fonctionnalité permettant de bloquer les accès à nos applications fronts depuis notre CDN suite à une alerte sur Datadog. Suite à ce blocage, un message est envoyé sur slack. Il n'existe actuellement pas de moyen de désactiver ce blocage autrement qu'en allant sur l'interface du CDN et de le désactiver pour chacun des frontaux. 
Ajouter un bouton dans le message Slack permettant de désactiver le blocage sur tous les frontaux.
- Exécuter la commande: `curl -X POST -H "Authorization: token" -H "Content-type:application/json" -d '{"eventId":"test1","body":">>{\"ip\":\"123.123.123.123\",\"ja3\":\"123455\"}<<"}' https://pix-bot-review-pr500.osc-fr1.scalingo.io/security/block-access-on-baleen-from-datadog
`
- Vérifier que le blocage est effectif pour l'application …

[FEATURE] Ajouter un bouton permettant de désactiver une règle de blocage auprès du CDN

---

build/services/merge-queue.js

Actuellement, nous avons des actions déclenchées plusieurs fois pour une même PR ce qui ne devrait pas arriver.
Ajouter des logs pour comprendre davantage ce qui se passe

[TECH] Ajouter des logs pour simplifier le debug de la merge queue

---

build/controllers/github.js
build/repositories/review-app-repository.js
common/services/github.js
test/acceptance/build/github_test.js
test/integration/build/repositories/review-app-repository_test.js
test/unit/build/controllers/github_test.js

Maddo a été ajouté à l'infrastructure backend de Pix et il est absent des review apps.
Déployer maddo avec l'ensemble des app du mono-repo.
Le déploiement de maddo n'est pas bloquant et le `check-ra-deployment` ne tient pas compte de son statut de déploiement. 
Faire confiance aux tests du repo, le coût des tests fonctionnels étant très important.

[FEATURE] Déploiement de maddo à la création/mise à jour des reviews app

---

build/templates/pull-request-messages/pix.md

MaDDo n’apparait pas dans le message posté par PixBot sur les PRs.
Ajouter MaDDo dans le template de message.
N/A
N/A

[BUGFIX] Ajouter MaDDo dans le message Github pix-bot

---

build/templates/pull-request-messages/pix-epreuves.md

On souhaite donner accès aux stats rollup sur les review apps pix-epreuves.
Ajouter un lien vers la page des stats rollup.
N/A
N/A

[FEATURE] Donner accès aux statistiques rollup sur les RAs pix-epreuves

---

config.js
test/unit/common/services/releases_test.js

Pix bot gère le déploiement des RAs pix-api-maddo, mais pas le déploiement de pix-api-maddo sur intégration, recette et production.
Ajouter api-maddo dans la liste des applications à déployer pour le monorepo.
En attente du merge de 1024pix/pix#11354
N/A

[FEATURE] Déployer l’application pix-api-maddo-{environment} (PIX-16552)

---

common/services/releases.js
config.js
run/services/slack/commands.js
test/unit/run/services/slack/commands_test.js

La commande `/deploy-last-version` ne fonctionne pas avec applications qui ont un tiret dans leur nom comme `audit-logger` ou `api-maddo`. 
Faire en sorte que la création du `shortAppName` fonctionne

[BUGFIX] Redeployer la dernière version d'une app comportant un tiret dans son nom

---

build/controllers/github.js

Il y a plusieurs semaines/mois le repository `pix-data-api-pix` a été renommé en `pix-api-to-pg` mais cela n'a pas été effectué dans Pix Bot. Il semblerait que les RA ne soient plus créées depuis.
Renommer `pix-data-api-pix` en `pix-api-to-pg`

[TECH] Renommer `pix-data-api-pix` en `pix-api-to-pg`

---

build/controllers/github.js
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js

Lorsque le label `no-review-app` est ajouté à la création de la PR, github envoie l'event `pull_request` avec l'action 'opened'. Dans le traitement qui est effectué, nous ne faisons rien si le label `no-review-app` est présent. Cependant, nous ne mettons pas à jour le commit status `check-ra-deployment` ce qui bloque le merge de la PR.   
Mettre à jour le commit status `check-ra-deployment` lorsque le label `no-review-app` est ajouté à la création de la PR.

[BUGFIX] Mettre à jour le commit status check-ra-deployment lorsque le label no-review-app est ajouté à la création de la PR.

---

common/repositories/release-settings.repository.js
db/migrations/20250305093326_add-release-settings-table.js
run/services/slack/shortcuts.js
run/services/slack/surfaces/modals/deploy-release/release-tag-selection.js
test/acceptance/run/slack_test.js
test/integration/common/repositories/release-settings.repository.test.js

On se dirige vers un système de mep automatique. Or, on a besoin de pouvoir bloquer ces mep à tout moment.
- Créer une table avec 4 colones (repositoryName, environment, authorizeDeployment, blockReason),
- Créer un repo,
- Ajuster le service d'envoie de release pour qu'il check si autorizeProd est sur true.
Il faudra ensuite rajouter un endpoint pour avoir une commande faisant basculer l'authorisation.
- Se rendre sur le slack de teste,
- Dans le chanel tech-releases, faire la commande pour déployer une mep /mep/deployer en s'assurant d'utiliser celle marquée avec pix-bot run pr 527,
- Exécutez ces commandes dans votre terminal pour modifier la valeur d'autorisation:
```shell
scalingo -a pix-bot-review-pr527 psql-console
```
Puis
```sql
UPDATE "release-settings" SET "authorizeDeployment" …
```

[FEATURE] Autoriser ou non les mises en production (PIX-16839)

---

build/controllers/github.js

Nous avons besoin d'ajouter une application front à pix-exploit.
Ajouter pix-exploit-front-review et renommer pix-exploit-review en pix-exploit-api-review

[TECH] Ajouter pix-exploit-front-review et renommer pix-exploit-review

---

build/templates/pull-request-messages/pix-exploit.md

On a oublié de mettre les liens vers les variables d'environnement de Pix exploit dans les templates de RA.
On les rajoutes!!!!
RAS

[BUGFIX] Ajouter les liens des variables d'environnement pour les pr de pix exploit (PIX-17107)

---

build/templates/pull-request-messages/pix-exploit.md

On avait modifié le template de Pix exploit pour inclure les liens vers les applications back et front. Or, on a décidé de tout mettre dans une seule application. Cela ne présente donc plus d'intérêt d'avoir plusieurs liens.
Revert les 2 commits faisant les modifications.

[REVERT] Revenir à l'ancien template pour Pix exploit

---

build/templates/pull-request-messages/pix-epreuves.md

On a ajouté un viewer de composants, mais le commentaire de PR ne contient pas de lien vers ce viewer.
Ajouter un lien.
N/A
N/A

[FEATURE] pix-epreuves: Lien vers le viewer de composants

---

build/templates/pull-request-messages/pix-epreuves.md

Le viewer d’épreuves a changé de nom de domaine.
Mettre à jour le nom de domaine dans le template de commentaire de PR pix-epreuves.
N/A
N/A

[FEATURE] Utiliser le nouveau nom de domaine du viewer pix-epreuves

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/unit/run/services/slack/commands_test.js

Actuellement, il n'y a pas de solution simple pour déployer l'application pix-securix-production.
Configurer une commande slack qui permette de créer la release et déployer l'application pix-secruix-production dans la foulée

[FEATURE]: Ajouter une commande slack de release et de déploiement pour l'application pix-securix.

---

config.js

Actuellement, le déploiement de securix en production définit l'application cible comme pix-securix-production. Cependent, le suffixe -production est ajouté en dur dans la méthode de déploiement. 
- Retirer le suffixe -production dans la configuration car il sera rajouté par le code.

[BUGFIX] Corriger le déploiement de securix

---

run/controllers/github.js
test/unit/run/controllers/github_test.js

Aujourd'hui, un webhook permet, suite à une release github, de déployer la version releasée d'une ou plusieurs applications. Cependant, le code actuel ne permet de déployer que sur secnum.
Permettre au webhook de release de déployer sur osc-fr1.

[FEATURE] Permettre au webhook de release de déployer sur osc-fr1

---

common/services/slack/surfaces/messages/post-message.js
config.js
run/services/tasks.js
run/services/tasks/release-production.js
sample.env
test/integration/run/services/tasks_test.js
test/unit/run/services/tasks/release-production_test.js

Maintenant que la mise en recette se fait toute seule. On souhaiterais pouvoir automatiser également la mise en production.
Ajouter une tâche de mise en production du dernier tag.
Le tag déployé est le dernier créé sur Github.
@MathieuGilet ?

[FEATURE] Lancer la mise en production automatiquement

---

run/services/tasks/release-production.js

Il y a une erreur dans la manière d'importer la fonction postMessage et de l'utiliser dans la tâche de mise en production de la release.
Corriger l'import et l'utilisation.
ON ne s'en était pas rendu compte à cause du teste unitaire.

[BUGFIX] Corriger l'appelle à la fonction d'envoie de message dans la tâche de mise en production

---

build/controllers/github.js

Aujourd'hui, nous déployons les review apps de `pix-db-replication`  depuis `pix-datawarehouse-integration` ce qui ne suit pas ce qui est fait sur les autres repository. Une application `pix-datawarehouse-review` a été créée afin de servir d'application template pour les review apps.  
Déployer les review apps de  `pix-db-replication` depuis `pix-datawarehouse-review`.
Suite au merge de cette PR il faudra peut être redéployer les review apps actuelles depuis `pix-datawarehouse-review`.

[TECH] Modifier l'application template pour les review apps de pix-db-replication

---

common/services/releases.js

Lors du refacto pour utiliser un logger pour Pix Bot, un `console.log` s'est vu devenir un `logger.error`, alors qu'il s'agit de la sortie standard. 
Repasser le log en level `info`.

[BUGFIX] Utiliser le bon level de log au moment des releases

---

common/controllers/index.js
common/repositories/applications-deployment.repository.js
common/routes/index.js
common/services/applications-deployment.service.js
db/migrations/20250603134355_create-table-applications-deployment.js
test/acceptance/common/index_test.js
test/integration/common/repositories/applications-deployment.repository.test.js
test/integration/common/services/applications-deployment.service.test.js

On souhaiterais savoir lorsque toutes les applications du monorepo sont déployée sur un environnement. Aujourd'hui, on est notifié par Scalingo à la fin du déploiement individuel de chaque app.
Créer une route post qui prend en payload le nom de l'app, le numéro de version et son environnement. Le tout sera sauvegardé en base et lorsque le déploiement de toutes les applications sera terminé, une notification Slack sera envoyée.
On était parti à l'origine sur Scalingo qui appelle cette nouvelle route à la fin de chaque déploiement. Cependant, étant donné qu'on ne peux pas choisir les paramètres qu'on souhaite y inclure (environnement par exemple), je pense que la solution idéale est de compléter l'action post-deploy avec un script qui fera un appel à l'url (en variable d'env) avec …

[FEATURE] Notifier via slack lorsque le déploiement des applications est terminé

---

common/controllers/index.js
common/repositories/applications-deployment.repository.js
common/services/applications-deployment.service.js
test/acceptance/common/index_test.js
test/integration/common/repositories/applications-deployment.repository.test.js
test/integration/common/services/applications-deployment.service.test.js

Scalingo envoie le nom complèt des applications, tel que pix-api-recettte ou pix-app-recette. Or on utilisait la config de pix-bot avec la variable PIX_APPS qui ne contient que la liste des applications sans sufix.
Inclure le sufix dans le nom des apps et dans les checks.
Rajouter les variables:
- RELEASE_CHANNEL_ID: l'identifiant du channel où il faudrat publier les messages sur la release.

[BUGFIX] Utiliser le nom complet des applications pour le déploiement

---

run/services/tasks/release-production.js
test/unit/run/services/tasks/release-production_test.js

Aujourd'hui, nous vérifions avant de MEP que la version releasée a bien build (comme cela est fait actuellement par la MEP via Slack). Nous avons cependant deux problèmes:
- Cette vérification n'a jamais fonctionné pour la MEP via Slack (méthode asychrone sans await).
- Le commit de release ne déclenche pas de build ([skip-ci] dans le commit)
Nous avons choisi de commenter le code afin de débloquer les MEP automatisées avant de trouver une solution plus pérenne.

[TECH] Commenter le code vérifiant que le build de la version releasée a bien fonctionné avant de MEP

---

common/services/applications-deployment.service.js
common/services/jira.service.js
config.js
sample.env
test/integration/common/services/jira.service.test.js

On souhaiterais que les tickets soient déplacés automatiquement dans Jira lorsque la mise en production d'une version est faite.
Ajouter un service jira qui va récupérer les version, chercher la version qui vient d'être déployée en prod et appeler l'api de jira pour finaliser la livraison de cette version. La livraison entraînera le déplacement des tickets.
J'ai aucune idée de si ça marche.
On tente ?

[FEATURE] releaser la version Jira  à la fin du déploiement d'une version en production

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js

On a besoin de passer par Scalingo pour déployer les tags de pix-exploit en production.
Ajouter une commande pix-bot pour déployer le dernier tag sur l'environnement de production.
Il faudra ajouter la commande à pix-bot-run.
TESTE effectué en local.

[FEATURE] Déployer pix-exploit depuis pix-bot

---

build/controllers/github.js
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js

On veut pouvoir beta tester un nouveau fonctionnement pour les reviews apps.
Ignorer les PRs labelisées Hera.
N/A
N/A

[FEATURE] Ignorer les PRs labelisées Hera

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

L’événement de fermeture de PR n’était pas géré.
Gérer les fermeture de PR Hera de la même manière que les autres PRs.
Fermer une PR Hera avec des applis cochées.

[TECH] Fermeture de PR Hera

---

db/migrations/20250725102927_remove-review-apps-isdeployed.js

La colonne `review-apps.isDeployed` n’est plus utilisée.
Supprimer la colonne.
N/A
N/A

[TECH] Supprimer la colonne `review-apps.isDeployed`

---

build/controllers/github.js
build/controllers/scalingo.js
build/repositories/review-app-repository.js
test/integration/build/repositories/review-app-repository_test.js
test/unit/build/controllers/github_test.js

Lors d’un synchronize, le déploiement des RAs est re-déclenché, mais le status (anciennement isDeployed) n’est pas correctement réinitialisé à pending en BdD.
Par conséquent, lors de la réception des événements de fin de déploiement de Scalingo, le status de check-ra-deployment n’est pas correctement calculé.
Autre problème :
Lorsque le webhook Scalingo appelle pix-bot-build-production pour une RA gérée par pix-bot-integration ou vice versa, cela provoque une erreur 500 car le RA n’existe pas en BdD.
Réinitialiser le status en BdD lors du synchronize.
Ne pas faire d’erreur 500 lorsque le webhook Scalingo appelle pour une RA inconnue en BdD.
Cette PR ne concerne que l’ancien fonctionnement (hors Hera).
N/A

[BUGFIX] Gérer le check-ra-deployment correctement lors d’un synchronize

---

build/controllers/github.js
common/services/scalingo-client.js
test/unit/build/controllers/github_test.js
test/unit/common/services/scalingo-client_test.js

Lorsqu’on créé une RA frontend, on a souvent un double déploiement :
- l’un déclenché par Scalingo avant que la désactivation du déploiement auto soit prise en compte
- l’autre déclenché manuellement par pix-bot
On souhaite éviter ce double déploiement, et en particulier celui déclenché par Scalingo.
Provisionner un addon Postgres sur les RAs frontend afin de rallonger leur temps de création et de permettre de prendre en compte la désactivation du déploiement auto avant que Scalingo déclenche un premier déploiement.
L’addon est supprimé par pix-bot juste après la création de la RA.
N/A
Testé sur 1024pix/pix#13063

[FEATURE] Supprimer les addons postgres provisionnés sur les fronts (monorepo)

---

common/services/github.js
test/unit/build/services/github_test.js

On récupère les infos de la PR trop souvent (notamment sur pix-bot-integration).
Mettre plus de vérification avant de récupérer les infos :
- vérifier que l’auteur du commentaire est de pix-bot
- vérifier que c’est une création de commentaire

[FEATURE] Éviter de récupérer les infos de la PR quand pas nécessaire

---

build/controllers/github.js
test/unit/build/controllers/github_test.js

Gérer le cas où la pullRequest est `undefined` lors d'un event d'édition d'issue comment.
https://github.com/1024pix/pix-bot/pull/624 cette PR est à l'origine du bug.
On passe volontairement pullRequest en `undefined` car on ne souhaite pas appeler github pour récupérer des infos si : 
- si ce n'est pas une pull request, 
- si l'auteur du commentaire n'est pas pix-bot-github
- à la création d'un commentaire

[BUGFIX] Gérer le cas où la pullRequest est undefined lors d'un event d'édition d'issue comment (TECHDAYS)

---

build/controllers/github.js
build/controllers/scalingo.js
build/repositories/review-app-repository.js
common/services/scalingo-client.js
test/acceptance/build/github_test.js
test/integration/build/repositories/review-app-repository_test.js
test/integration/build/scalingo_test.js
test/integration/run/services/slack/commands_test.js
test/unit/build/controllers/github_test.js
test/unit/common/services/scalingo-client_test.js

Le check-ra-deployment passe vert trop tôt quand on fait des déploiements rapprochés (2 pushs successifs par ex.).
Changer le status de la RA en BdD seulement si l’appel de webhook concerne le dernier déploiement.

[FEATURE] Amélioration du check-ra-deployment

---

build/templates/pull-request-messages/pix-data.md

Il y a des subtilités à prendre en compte lors de l'utilisation des RA Airflow.
Ajouter les tips au template du message envoyé sur les PR pix-data.
Déployer pix-bot sur l'intégration, [ouvrir une PR sur pix-data ](https://github.com/1024pix/pix-data/pull/968)avec le label `pix-bot-integration` vérifier le message.

[FEATURE] Ajouter des astuces au message du dépôt pix-data

---

build/controllers/github.js
test/acceptance/build/github_test.js
test/unit/build/controllers/github_test.js

Quand on coche plusieurs apps dans le commentaire, il y a des race conditions entre les appels de webhook successifs.
Github ne garantit pas l’ordre d’appel, donc la comparaison du commentaire avec la BdD ne peut pas être 100% fiable.
La payload du webhook contient la version précédente du commentaire, on l’utilise pour faire un diff au lieu de comparer avec la BdD.
N/A
N/A

[BUGFIX] Éviter les race conditions d’édition de commentaire

---

config.js
run/controllers/slack.js
run/manifest.js
run/services/slack/commands.js
test/acceptance/run/manifest_test.js
test/unit/run/services/slack/commands_test.js

La commande slack `/publish-pix-ui` n’est plus utilisée.
Supprimer la commande.

[FEATURE] Suppression de la commande slack `/publish-pix-ui`

---

build/controllers/github.js

On a quasi systématiquement des doubles déploiements sur pix-epreuves.
Mettre en place le contournement pour éviter les doubles déploiements sur pix-epreuves.
N/A
Test sur 1024pix/pix-epreuves#2690

[TECH] Éviter les doubles déploiements sur pix-epreuves
