1024pix/pix-bot

- .eslintrc.js
- lib/controllers/slack.js
- lib/services/github.js
- lib/services/google-sheet.js
- lib/services/releases.js
- lib/services/slack/surfaces/modals/deploy-release/release-deployment-confirmation.js
- lib/services/slack/surfaces/modals/deploy-release/release-tag-selection.js
- lib/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
- lib/services/slack/surfaces/modals/publish-release/release-type-selection.js
- lib/services/slack/view-submissions.js
- package-lock.json
- package.json
- test/get-pull-requests-to-release-in-prod_test.js
- test/unit/services/github_test.js
- test/unit/services/google-sheet_test.js
- test/unit/services/releases_test.js
- test/unit/services/scalingo-client_test.js
- test/unit/services/slack/commands_test.js
Ajout de la configuration d'eslint et correction des errreurs de lint.
> Configuration d'ESLint et correction des erreurs de lint

- lib/services/releases.js
- lib/services/slack/commands.js
- test/unit/services/releases_test.js
- test/unit/services/slack/commands_test.js
Comme pour Pix-Site, utilisation des GitHub archives et de Scalingo CLI pour déployer l'application pix-pro
> [FEATURE] Deploy pix site pro with GitHub archives and Scalingo CLI

- docs/pull_request_template.md
- package-lock.json
- package.json
1. Add a template for PRs like pix repo.
2. Upgrade all project dependencies to the last version
> [BSR] Add PR template and upgrade dependencies

- common/services/scalingo-client.js
Il y a une typo dans le code
Corriger la typo environement -> environment
> [TECH] Corrige une typo

- build/controllers/github.js
Suite à la création du nouveau repo pix-tutos, nous souhaitons ajouter les reviews app afin de tester convenablement les fonctionalités
Ajouter le nouveau repo au mapping existant dans pix-bot
N/A
> [FEATURE] Ajouter les review apps pour pix-tutos (PIX-5030)

- package-lock.json
- package.json
- scripts/publish.sh
Le déploiement en recette échoue sur la création de la release sentry. Le cli est installé par pix-bot mais on l'utilise dans le context de l'application Pix.
Installer @sentry/cli directement avec la bonne version 
...
> [BUGFIX] Corrige le déploiement en recette

- common/services/github.js
Assez peu lisible de fournir les paramètres à l'API GitHub.
Faciliter la lecture en construisant la string à partir d'un objet.
RAS
Les tests auto devraient couvrir ça.
> [DX] Construction query string Octokit via function

- package-lock.json
L'application crashe lorsque nous avons une opération d'extinction/rallumage des reviews apps. Le bugfix a été fait sur le package `scalingo-review-app-manager`.
Mettre à jour le paquet.
:shrug:
> [BUGFIX] Mise à jour de scalingo-review-app-manager

- package-lock.json
Certaines dépendances ne sont pas à jour.
Mettre à jour.
npm test
> [TECH] Mise à jour des dépendances

- .github/renovate.json
Les packages ne sont pas mis à jour automatiquement, ni manuellement.
Utiliser renovate
Voir [ADR](https://github.com/1024pix/pix/pull/5329)
Merger et vérifier que la dépendance suivante est mise à jour
```
❯ npm outdated
Package   Current  Wanted  Latest  Location               Depended by
prettier    2.8.0   2.8.1   2.8.1  node_modules/prettier  pix-bot
```
> Mettre à jour automatiquement l'environnement

- .github/renovate.json
Pas besoin de review-app car on cible l'automerge si test OK
Le lable dependencies n'est pas clair
Ajouter des labels dans la config
Merger
> Signaler clairement les PR renovate

- .github/renovate.json
L'intégration Github/Renovate est trop complexe pour activer l'auto-review et l'auto-merge.
Ne plus utiliser la configuration partagée.
Comme il y a le label "Ready to merge", il suffit de review
Merger
> [TECH] Créer automatiquement des PR de montées de version

- package.json
- test/acceptance/common/index_test.js
La description de l'application n'est pas claire.
L'expliciter
Correction de l'indice du script de démarrage
Relire
> [TECH] Expliciter la description de l'application

- build/controllers/github.js
- build/templates/pull-request-messages/default.md
- build/templates/pull-request-messages/pix-db-replication.md
- build/templates/pull-request-messages/pix-site.md
- build/templates/pull-request-messages/pix.md
- test/unit/build/controllers/pull-request-messages/pix-bot.md
- test/unit/build/controllers/pull-request-messages/pix-db-replication.md
- test/unit/build/controllers/pull-request-messages/pix-editor.md
- test/unit/build/controllers/pull-request-messages/pix-site.md
- test/unit/build/controllers/pull-request-messages/pix.md
Les commentaires de PR comportent des quotes inutiles, des https manquants, etc..
Corriger
Ca arrive
Vérifier la CI
> [BUGFIX] Les commentaires de PR non sont pas tout à fait corrects

- build/templates/pull-request-messages/pix-db-replication.md
- build/templates/pull-request-messages/pix-editor.md
- test/unit/build/controllers/pull-request-messages/pix-db-replication.md
- test/unit/build/controllers/pull-request-messages/pix-editor.md
Suite de https://github.com/1024pix/pix-bot/pull/204
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._
> [BUGFIX] Les commentaires de PR ne toujours sont pas tout à fait corrects 

- config.js
- run/controllers/slack.js
- run/manifest.js
- run/services/slack/commands.js
- test/acceptance/run/manifest_test.js
- test/acceptance/run/slashcommand_test.js
- test/integration/run/services/slack/commands_test.js
Pix 360 n'est pas déployé par pix-bot.
Le faire déployer la branch main
> [FEATURE] Déploie pix 360 depuis pix-bot

- build/controllers/github.js
Airflow n'est pas déployé avec pix-bot, ce qui oblige à créer des RA manuelles
Les créer automatiquement
Ne déployer que Airflow
Merger et MEP.
Créer une PR sur [pix-data](https://github.com/1024pix/pix-data).
Vérifier que les liens cont corrects.
> [FEATURE] Déployer airflow

- build/controllers/github.js
- test/acceptance/build/github_test.js
Les RA ne se recréent pas en cas de réouverture de PR
Ajouter l'évènement
Les tests sont modifiés pour éviter la duplication de code
> Créer des RA en cas de réouverture de PR

- config.js
- run/controllers/slack.js
- run/manifest.js
- run/services/slack/commands.js
- test/acceptance/run/manifest_test.js
- test/acceptance/run/slashcommand_test.js
- test/integration/run/services/slack/commands_test.js
L'application data-build-tools n'a pas d'automatisation pour ses  mises à jour.
L'ajouter via slack
> Ajouter une slash command slack sur les déploiements de DBT

- config.js
- test/unit/common/services/releases_test.js
Pix1d n'est pas déployé lors de la MER/MEP
Le déployer en mettant à jour la configuration
Merger et faire une MER/MEP
> [FEATURE] Déployer pix1d (PIX-8336)

- build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
- test/acceptance/build/slack_test.js
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._
> [BUGFIX] :bug: Corriger le lien vers le diff dans la vue Slack release-publication-confirmation

- common/services/github.js
- test/acceptance/run/slack_test.js
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._
> [TECH] Amélioration de la gestion des appels en échec lors de la récupération des derniers tags

- run/deploy-configuration.js
- test/acceptance/run/manifest_test.js
- test/acceptance/run/slashcommand_test.js
Privatebin n'a pas de slash command pour ses mises à jour sur Scalingo
l'ajouter
> Ajouter le déploiement de Privatebin depuis slack

- build/templates/pull-request-messages/pix-epreuves.md
Le message doit évoluer pour la mise en place de l'oauth2 pour le viewer.
Changer le template de message en conséquence.
N/A
N/A
> [FEATURE] Mise à jour du message du bot pour pix-epreuves

- build/templates/pull-request-messages/pix.md
Pix 1D à enfin un nom ! \o/
Renommer 1d en Junior
> [TECH] Renomme 1d en Junior

- common/services/github.js
- test/unit/build/services/github_test.js
Les événements de revue `CHANGES_REQUESTED` peuvent être revues en [`APPROVE`](https://api.github.com/repos/1024pix/pix/pulls/8620/reviews) ou [`DISMISSED`](https://api.github.com/repos/1024pix/pix/pulls/8511/reviews). Pour le moment on continue d'afficher des croix rouges :x: dans ce cas là.
Ne plus considérer qu'il y a des changements nécessaires si la review d'un user a été revue.
RAS
CI verte.
> [BUGIFX] Ne pas afficher les `CHANGES_REQUESTED` si ils ont été traités

- server.js
La route merge n'est pas ajouté au router
On ajoute la route au router
ras
on merge
> [BUGFIX] Ajouter la route merge dans les routes du serveur

- config.js
L'environnement d'integration de maddo ne se met pas à jour tout seul 
Ajouter dans la config pour que ça se fasse comme il faut
> [FEATURE] Ajouter maddo dans la liste des apps à déployer en integration. 

- package-lock.json
- package.json
Si on souhaite faire du dev en continue sur Pix Bot on doit redémarrer à chaques modifications.
- Ajouter nodemon,
- Ajouter une commande pour lancer le projet en mode dev.
RAS
En local, faire la commande suivante:
```shell
npm run dev
```
Modifier quelque chose dans le code et constater que l'application redémarre.
> [TECH] Ajouter nodemon et une commande pour lancer Pix Bot en mode dev

- build/controllers/github.js
Nous ne souhaitons plus avoir une application front et une application back pour pix-exploit.
Ne pas déployer de pix-exploit-front-review-pr-*
> [TECH] Ne pas déployer de pix-exploit-front-review-pr-*

- build/controllers/github.js
On a un nouveau repo securix qui va utiliser les review app.
L'ajouter à la liste des repositories.
> [FEATURE] Ajouter le repo securix

- run/services/tasks/release.js
Suite au merge de la PR https://github.com/1024pix/pix-bot/pull/549, du code inutile a été mergé par erreur. 
Supprimer le code inutile.
> [BUGFIX] Supprimer du code inutile

- common/services/applications-deployment.service.js
> [BUGFIX] Corriger une typo

- build/controllers/github.js
- common/services/github.js
- config.js
- test/acceptance/build/github_test.js
- test/unit/build/controllers/github_test.js
- test/unit/build/services/github_test.js
On veut pas taper sur la prod avec notre chantier.
Permettre de pouvoir tester Pix Bot Integration 🤖
:)
> [FEATURE] Permettre de pouvoir tester Pix Bot Integration 🤖

- build/controllers/github.js
- build/templates/pull-request-messages/hera/default.md
- build/templates/pull-request-messages/hera/pix.md
- test/unit/build/controllers/github_test.js
On peut commencer le chantier de ra à la demande coté pix bot :) 
On commence par la création du commentaire qui sera composé de checkboxs pour sélectionner les apps Scaling à deploy
si on est content du code, on merge
> [FEATURE] Créer un message spécifique en cas de création de pull request labelisée Hera (tech-days).

- build/controllers/github.js
- build/repositories/review-app-repository.js
- test/integration/build/repositories/review-app-repository_test.js
- test/unit/build/controllers/github_test.js
L’action synchronize ne déclenche pas de redéploiement sur les PR Hera.
Gérer l‘action synchronize.
Faire un push sur 1024pix/pix#12971
> [FEATURE] Gérer l’action synchronize sur les PR Hera

- build/controllers/github.js
- build/templates/pull-request-messages/pix-api-data-pix.md
Code pour un repo archivé.
Le supprimer.
> [TECH] Supprimer un repo archivé

- build/controllers/github.js
- build/templates/pull-request-messages/hera/default.md
- build/templates/pull-request-messages/hera/pix-4pix.md
- build/templates/pull-request-messages/hera/pix-api-data-replication.md
- build/templates/pull-request-messages/hera/pix-data.md
- build/templates/pull-request-messages/hera/pix-editor.md
- build/templates/pull-request-messages/hera/pix-epreuves.md
- build/templates/pull-request-messages/hera/pix-exploit.md
- build/templates/pull-request-messages/hera/pix-nina.md
- build/templates/pull-request-messages/hera/pix-site.md
- build/templates/pull-request-messages/hera/pix-tutos.md
- build/templates/pull-request-messages/hera/pix.md
- test/unit/build/controllers/github_test.js
Il faut éditer chacun des templates pour lister les RA à déployer.
Générer cette partie du message.
> [FEATURE] Générer les checkbox de déploiement des RA
